- splunk_add_on_ucc_framework/__init__.py
Fixed the following error in UCC
> Fixed install-lib error when lagecy requirement.txt location is provided

- splunk_add_on_ucc_framework/__init__.py
- Updated remove_listed_files method to ignore files and folder.
> updating remove_listed_files method

- README.md
As a part of this PR, the following has been implemented
- Added a new line in Readme.md file to fix table issue in documentation.
> Added a new line to fix table issue

- splunk_add_on_ucc_framework/__init__.py
Summary:
- Fix for the issue raised https://splunk.slack.com/archives/GSZDDN1GF/p1606711001369100?thread_ts=1606482636.366500&cid=GSZDDN1GF
- Added dynamic generated License header in app.conf.
> License header in app.conf

- .circleci/config.yml
- .github/workflows/cla.yaml
- .github/workflows/release-notes.yaml
- README.md
- splunk_add_on_ucc_framework/__init__.py
- Added Support for additional packaging
> Added support for additional packaging

- poetry.lock
Bump splunktaucclib to v4.0.13
> fix: bump splunktaucclib to 4.0.13

- splunk_add_on_ucc_framework/ucc_ui_lib/package.json
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/TestComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/axiosCallWrapper.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/util.js
- splunk_add_on_ucc_framework/ucc_ui_lib/yarn.lock
- added axios call wrapper and some cleanup
> ADDON-34285: ucc-ui-lib: added axios call wrapper

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/MultiInputControl.jsx
Jira Link: https://jira.splunk.com/browse/ADDON-34280
Changes:
* Added new MulitSelectControl Component
> Add mulitselect compomemt

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/SingleInputControl.jsx
Jira Link: https://jira.splunk.com/browse/ADDON-34278
Changes:
Added new SingleSelectControl Component
> ADDON-34278: Add singleselect component

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/constants/preDefinedRegex.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/Validator.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/uccConfigurationValidators.js
[ADDON-34291](https://jira.splunk.com/browse/ADDON-34291)
- Created Predefined Validators for entity type - string, regex, number, URL, email, ipv4 and date.
- **doValidation** method of class **Validator** checks for validation based on entity type and returns dictionary containing error and errormsg if any.
> ADDON-34291: Added Validation utility

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/CustomTable.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/CustomTableStyle.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableExpansionRow.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableWrapper.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/EntryPageStyle.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/Input/InputPage.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/entry_page.jsx
JIRA Ticket: https://jira.splunk.com/browse/ADDON-34131
> ADDON-34131: Pagination component implemented

- splunk_add_on_ucc_framework/ucc_ui_lib/package.json
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/ErrorBoundary.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/CustomTable.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableWrapper.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/constants/errorCodes.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/context/InputRowContext.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/errors/errorWithCode.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/Input/InputPage.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/entry_page.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/axiosCallWrapper.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/util.js
- splunk_add_on_ucc_framework/ucc_ui_lib/yarn.lock
https://jira.splunk.com/browse/ADDON-34750
- Added data loading in table
- Added endpoint calls for input status toggle
- Added error handling with toast message and `ErrorBoundary`
- Fixed padding issue with input status toggle
- Fixed data handling when no data available for table
- Updated `axiosCallWrapper` to accept object with required properties in function argument
> Addon 34750 dynamic data loading

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/BaseFormView.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/ControlWrapper.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/CustomControl.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/EntityModal.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/HelpLinkComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/TextComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/constants/ControlTypeMap.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/constants/modes.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/Input/InputPage.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/entry_page.jsx
-Added `Create input button`
-Added `Custom Control ` initial Code
jira link : ADDON-34744
> Feature/addon 34744 ucc splunk UI migration custom control implementation in form

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/BaseFormView.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/CustomControl.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/EntityModal.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/TextComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/Validator.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/uccConfigurationValidators.js
[ADDON-34763](https://jira.splunk.com/browse/ADDON-34763)
- Integrated validations in Submit event of form
- Added Custom validator for Custom Control
> Integrate validations with form

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/BaseFormView.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/ControlWrapper.jsx
Jira: https://jira.splunk.com/browse/ADDON-34743
Changes:
* Implemented dependent field login the form
> Implemented dependent field login the form

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/BaseFormView.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/ControlWrapper.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/DeleteModal.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/EntityModal.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/SingleInputComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/CustomTable.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/Input/InputPage.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/messageUtil.js
- handled EDIT/CLONE and DELETE button
[jira link](https://jira.splunk.com/browse/ADDON-34746)
> Addon 34746 submit button in form

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/resources/splunk/appserver/templates/base.html
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/ControlWrapper.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/CustomCell.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/CustomTable.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/CustomTableStyle.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableWrapper.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/Input/InputPageStyle.jsx
JIRA Ticket:  https://jira.splunk.com/browse/ADDON-34742
- Custom cell implementation in the table component
- Fixed sorting issue
> feat: Added custom cell feature in the table and fixed sorting issue

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/CustomControl.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/DeleteModal.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/EntityModal.jsx
[jira link](https://jira.splunk.com/browse/ADDON-34744)
- Added loading in custom control
> ADDON-34744:Added loading in custom control

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/BaseFormView.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/CheckBoxComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/util.js
[ADDON-35152](https://jira.splunk.com/browse/ADDON-35152)
- Updated Selected property of switch component which will be selected if the prop. value is **"1", 1 or true.** 
- Updated Default value fetching in form components
> ADDON-35152:Updated selected property

- splunk_add_on_ucc_framework/ucc_ui_lib/design_changes.patch
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/resources/splunk/appserver/templates/base.html
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/ControlWrapper.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/DeleteModal.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/MultiInputComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/RadioComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/SingleInputComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/TextComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/CustomTable.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/CustomTableControl.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/CustomTableRow.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableExpansionRow.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableFilter.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableHeader.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableWrapper.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/Configuration/ConfigurationPage.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/EntryPageStyle.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/Input/InputPage.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/configManager.jsx
JIRA Ticket: https://jira.splunk.com/browse/ADDON-35091
- Implemented a custom row feature
- Implemented a pure component for table row
- Fixed the design issue in the table header component
- Fixed the loading (Spinner) issue while refreshing the page
- Set the background color of the body
- Added debounce in the text row filter
- Form design changes
- Some style changes in the application level
> ADDON-35091: Custom row feature implemented

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/BaseFormView.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/EntityModal.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/Validator.js
[jira link](https://jira.splunk.com/browse/ADDON-35095)
- implemented custom hook feature
> Feature/addon 35095 ucc splunk UI migration custom hook implementation

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/constants/messageDict.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/configManager.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/util/script.js
[ADDON-35088](https://jira.splunk.com/browse/ADDON-35088)
- Updated **globalConfig.json** loading using axios
> ADDON-35088: Updated globalConfig.json loading

- tests/unit/test_config_validation.py
- tests/unit/testdata/invalid_config_no_configuration_tabs.json
- tests/unit/testdata/valid_config.json
> tests: add schema validation unit tests

- .ucc-ui-version
> Update UCC UI Version

- .ucc-ui-version
> Update UCC UI to v1.5.0

- .ucc-ui-version
> Update UCC UI to v1.5.7

- pyproject.toml
fix: include schema and notice file in pip package
> fix: include schema and notice file in pip package

- .ucc-ui-version
Aggregated Changelog from UI [repo](https://github.com/splunk/addonfactory-ucc-base-ui/releases):
- fixed UI breaking when globalConfig does not have inputs config
- keep only one-way routing with query params
- enhanced toast messages
- fixed an issue specific to OAuth fields where the field was required but the placeholder showed "optional"
- added support for "placeholder" entity type
- enhanced error page UI/UX
- version bumps to few JS libraries
> feat: update ucc ui version to v1.7.2

- .github/workflows/agreements.yaml
Fixes https://github.com/splunk/addonfactory-ucc-generator/pull/225/checks?check_run_id=2811076190.
> build: fix CLA assistant version

- poetry.lock
- pyproject.toml
> fix: remove splunktalib as not used

- .ucc-ui-version
UI Fixes:
- pass empty string to i18n if the field is optional in `globalConfig.json`
- load dependent fields on form create
- cleared fields for other authentication methods when using one in oauth configuration
> Update ucc ui version to v1.7.5

- .ucc-ui-version
UI fixes:
- enforce logic for displaying clear button for singleselect when its disabled
> fix: update ucc version to 1.7.6

- .ucc-ui-version
Features:
- Added missing support for label in ComboBox ([ADDON-37036](https://jira.splunk.com/browse/ADDON-37036))
- Added support for `required` param in OAuth config ([ADDON-38644](https://jira.splunk.com/browse/ADDON-38644))
> feat: update ucc ui version

- .github/workflows/build-test-release.yml
From official docs: https://github.com/github/super-linter#slim-image
> build: use super-linter slim version

- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/conf_parser.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/event_writer.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/memory_event_writer.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/metric_aggregator.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/metric_exception.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/metric_util.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/monitor.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/number_metric_collector.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/__init__.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_base.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_conf_gen.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_html_gen.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_py_gen.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_template.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/cim_actions.py
- splunk_add_on_ucc_framework/normalize.py
- splunk_add_on_ucc_framework/start_alert_build.py
- splunk_add_on_ucc_framework/uccrestbuilder/builder.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/base.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/datainput.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/field.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/oauth_model.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/single_model.py
- splunk_add_on_ucc_framework/uccrestbuilder/global_config.py
- splunk_add_on_ucc_framework/uccrestbuilder/rest_conf.py
- tests/unit/helpers.py
- tests/unit/test_config_validation.py
This PR is a result of using [pyupgrade](https://github.com/asottile/pyupgrade) with `--py3-plus` option.
Also removed unused code and fixed `intent` function after running `pyupgrade`.
> refactor: run pyupgrade

- poetry.lock
- pyproject.toml
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/base.py
- tests/unit/test_uccrestbuilder.py
`io.StringIO` wrapper around lines is needed to handle cases when `lines` is equal to `None`.
Also added couple of tests not to mess things in the future.
> fix: issue with indent function

- .pre-commit-config.yaml
- README.md
- poetry.lock
- pyproject.toml
Please visit https://pre-commit.com/#quick-start for more details regarding `pre-commit`.
> chore: add pre-commit

- .github/workflows/build-test-release.yml
- .pre-commit-config.yaml
- pyproject.toml
- splunk_add_on_ucc_framework/uccrestbuilder/global_config.py
- tests/unit/test_config_validation.py
- tests/unit/test_uccrestbuilder.py
Now, there should not be any conflict between black and isort in terms of sorting imports.
> refactor: apply isort changes and introduce isort in pre-commit

- .ucc-ui-version
* handle value `undefined` in table sort ([2416eb8](https://github.com/splunk/addonfactory-ucc-base-ui/commit/2416eb83844e2720e669a4d6e7a60429de64c93b)) [ADDON-39208](https://jira.splunk.com/browse/ADDON-39208)
* parse boolean of `disabled` before setting it in state ([4171699](https://github.com/splunk/addonfactory-ucc-base-ui/commit/41716994ee213f83dd1c182703a2023da4331c8e)) [ADDON-39125](https://jira.splunk.com/browse/ADDON-39125)
> fix: update ucc ui version to 1.8.3

- .github/workflows/build-test-release.yml
- .releaserc
> ci: bump version after release

- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/meta_conf.py
- tests/data/package_global_config_configuration/globalConfig.json
- tests/data/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/data/package_global_config_inputs_configuration_alerts/package/metadata/default.meta
- tests/data/test_ucc_generate.py
- tests/expected_output_global_config_configuration/Splunk_TA_UCCExample/metadata/default.meta
- tests/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/metadata/default.meta
- tests/expected_output_no_global_config/Splunk_TA_UCCExample/metadata/default.meta
- tests/unit/test_meta_conf.py
Related to https://github.com/splunk/addonfactory-ucc-generator/issues/267
> feat: generate metadata/default.meta

- .github/workflows/sr-prepare.sh
- .releaserc
- splunk_add_on_ucc_framework/uccrestbuilder/__init__.py
Closes #315.
Fixes releasing process and using semantic-release bot to dump version after release.
> fix: releasing process

- .github/workflows/check_ucc_ui_files.sh
- splunk_add_on_ucc_framework/__init__.py
Change `.github/workflows/check_ucc_ui_files.sh` to work with dynamic version after `poetry build` command.
> ci: fix issues after merges

- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_html_gen.py
- tests/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/default/data/ui/alerts/test_alert.html
- tests/unit/test_alert_actions_html_gen.py
- tests/unit/testdata/alert.html.generated
> fix: alert html generation

- .licenserc.yaml
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_conf_default_settings.json
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_conf_gen.py
- tests/data/test_ucc_generate.py
- tests/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/default/alert_actions.conf
- tests/unit/test_alert_actions_conf_gen.py
- tests/unit/test_alert_actions_html_gen.py
- tests/unit/test_alert_actions_py_gen.py
- tests/unit/testdata/alert_actions.conf.generated
> fix: add icon_path to each modular alert conf

- LICENSE
Based on the legal support team.
> chore: update copyright statement in LICENSE

- .github/workflows/build-test-release.yml
- .pre-commit-config.yaml
We don't need `actionlint` anymore.
> chore: remove actionlint

- splunk_add_on_ucc_framework/__init__.py
> fix: no crash if metadata folder exists

- splunk_add_on_ucc_framework/__init__.py
> fix: better exception handling when could not get the version from git tags

- splunk_add_on_ucc_framework/meta_conf.py
- tests/data/package_global_config_inputs_configuration_alerts/package/metadata/default.meta
- tests/expected_output_global_config_configuration/Splunk_TA_UCCExample/metadata/default.meta
- tests/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/metadata/default.meta
- tests/expected_output_no_global_config/Splunk_TA_UCCExample/metadata/default.meta
Idea from: https://github.com/splunk/splunk-add-on-for-mysql/pull/327
> feat: add sc_admin to default.meta

- docs/how_to_use.md
- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/install_libs.py
- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/unit/test_install_python_libraries.py
> feat: add --python-binary-name flag to specify Python name to install libraries

- .github/workflows/docs.yml
- docs/how_to_use.md
- poetry.lock
- pyproject.toml
This PR adds a link to the JSON schema for `globalConfig.json` and updates the Github Actions workflow to use poetry to install docs dependencies.
> docs: update workflow and mention JSON schema

- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/exceptions.py
- splunk_add_on_ucc_framework/utils.py
- tests/unit/test_utils.py
This PR moves the code which is responsible for the getting add-on version using git to another file and adds some unit tests for it.
> refactor: move git version parsing to a separate function

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- CONTRIBUTING.md
- README.md
- docs/contributing.md
- docs/example.md
- docs/how_to_use.md
- docs/index.md
- docs/troubleshooting.md
- mkdocs.yml
This PR adds contributing guide pages, new templates for bugs and feature in GitHub.
> docs: add contributing guide

- .github/ISSUE_TEMPLATE/feature_request.yml
> docs: fix feature request template

- .github/ISSUE_TEMPLATE/feature_request.yml
> docs: update feature request template

- docs/example.md
- docs/how_to_use.md
- docs/index.md
- docs/tabs.md
- mkdocs.yml
How to use page, index page, created new "Tags" page.
> docs: multiple updates

- pyproject.toml
- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/__main__.py
- splunk_add_on_ucc_framework/main.py
- tests/unit/test_main.py
> refactor: rework ucc-gen entrypoint and add tests

- docs/troubleshooting.md
- poetry.lock
> docs: update mkdocs versions

- .pre-commit-config.yaml
- docs/example.md
- docs/how_to_use.md
- poetry.lock
- pyproject.toml
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/global_config_update.py
- splunk_add_on_ucc_framework/global_config_validator.py
- tests/unit/helpers.py
- tests/unit/test_config_validation.py
- tests/unit/test_global_config_update.py
- tests/unit/testdata/config_with_biased_terms.yaml
- tests/unit/testdata/invalid_config_no_configuration_tabs.yaml
- tests/unit/testdata/invalid_config_no_name_field_in_configuration_tab_table.yaml
- tests/unit/testdata/valid_config.yaml
- Added support for globalConfig.json and globalConfig.yaml file
- Added unit tests for the same
> ADDON-56381: Added support for YAML file

- get-ucc-ui.sh
Included changes:
* added tabs feature in the Inputs page
* fixed the line breaker issue
* support custom REST handlers from the schema perspective
* fixed the custom menu with style property related issue
> feat: update UCC UI to v1.14.1

- splunk_add_on_ucc_framework/commands/rest_builder/validator_builder.py
- splunk_add_on_ucc_framework/global_config_validator.py
- tests/unit/test_global_config_validator.py
- tests/unit/testdata/invalid_config_json_is_missing_in_supported_file_types.json
- tests/unit/testdata/invalid_config_supported_file_types_field_is_missing.json
- tests/unit/testdata/invalid_config_validators_missing_for_file_input.json
- tests/unit/testdata/valid_config.json
- tests/unit/testdata/valid_config.yaml
This is a follow up PR after initial implementation of file component in UCC UI.
> feat: validate file component

- poetry.lock
- pyproject.toml
Closes #592
Closes #580
Closes #579
> chore: add importlib-metadata for Python 3.7

- .releaserc
Similar to https://github.com/splunk/pytest-splunk-addon/pull/444
> ci: update release configuration

- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/unit/test_install_python_libraries.py
Updating the file or directory checks using `isfile` and `isdir` of the `os.path` module.
> chore(code): update file, dir checks condition

- .github/workflows/build-test-release.yml
- poetry.lock
Updating some of the Python dependencies and update splunk-release-action.
> chore: update deps

- docs/example.md
Missed this change after the recent docs rework.
> docs: bugfix for changed link

- docs/tabs.md
This PR is related to this code changes - https://github.com/splunk/addonfactory-ucc-base-ui/pull/239
> docs: ADDON-58705 Doc changes for the table action field

- .github/workflows/build-test-release.yml
- splunk_add_on_ucc_framework/global_config_validator.py
- tests/unit/test_global_config_validator.py
- tests/unit/testdata/invalid_config_configuration_autoCompleteFields_duplicates.json
- tests/unit/testdata/invalid_config_configuration_children_duplicates.json
- tests/unit/testdata/invalid_config_configuration_entity_duplicates.json
- tests/unit/testdata/invalid_config_configuration_tabs_duplicates.json
- tests/unit/testdata/invalid_config_inputs_autoCompleteFields_duplicates.json
- tests/unit/testdata/invalid_config_inputs_children_duplicates.json
- tests/unit/testdata/invalid_config_inputs_entity_duplicates.json
- tests/unit/testdata/invalid_config_inputs_services_duplicates.json
Moved global config json duplicates validators from the ucc-ui repo to ucc-gen repo in python
> feat: move validators from ucc-ui to ucc-gen

- poetry.lock
- pyproject.toml
> docs: update mkdocs-material

- example/globalConfig.json
- poetry.lock
- pyproject.toml
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
Updating PSA, Smartx and pytest.
> chore: update pytest and smartx

- .addonmatrix
- .github/workflows/build-test-release.yml
- run_splunk.sh
Run UCC UI tests in the UCC repo.
> ci: run UI tests on multiple Splunk versions

- .github/workflows/build-test-release.yml
This should help our life easier and pipeline to run faster for most of the use cases.
> ci: run UI tests only when label is present

- .github/workflows/build-test-release.yml
- example/globalConfig.json
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/default/data/ui/alerts/test_alert.html
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/ui/conftest.py
- tests/ui/pages/alert_action_page.py
- tests/ui/pytest.ini
- tests/ui/test_account_page.py
- tests/ui/test_alert_actions_page.py
- tests/unit/test_alert_actions_conf_gen.py
- tests/unit/test_alert_actions_html_gen.py
- tests/unit/test_alert_actions_py_gen.py
- tests/unit/testdata/alert.html.generated
- tests/unit/testdata/valid_config.json
- tests/unit/testdata/valid_config.yaml
This PR adds new UI tests for alert actions page.
> test: introduce UI tests for alert actions page

- .github/workflows/build-test-release.yml
This will make bot to sign commits so we do not have issues with rebasing anymore.
> ci: update release action

- .github/workflows/build-test-release.yml
- example/globalConfig.json
- poetry.lock
- pyproject.toml
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/bin/example_input_two.py
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_example_input_one.py
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_example_input_two.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/ui/pages/input_page.py
- tests/ui/pytest.ini
- tests/ui/test_input_page.py
Onboarding last set of UI tests - for the input page.
> test: introduce more tests for input page

- get-ucc-ui.sh
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/ui/test_account_page.py
Updating UCC UI to the latest version.
> feat: update UCC UI to v1.23.1

- example/globalConfig.json
- splunk_add_on_ucc_framework/global_config_validator.py
- splunk_add_on_ucc_framework/normalize.py
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/default/data/ui/alerts/test_alert.html
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/unit/test_alert_actions_html_gen.py
- tests/unit/testdata/alert.html.generated
- tests/unit/testdata/valid_config.json
- tests/unit/testdata/valid_config.yaml
Jira link: https://splunk.atlassian.net/browse/ADDON-61339
> feat: initial version of earliest/latest support for alerts

- .github/workflows/build-test-release.yml
- mkdocs.yml
This check will allow us to spot any problems with docs before we merge the PR.
> ci: introduce docs-build step to verify docs

- example/globalConfig.json
- splunk_add_on_ucc_framework/app_conf.py
- tests/smoke/test_ucc_build.py
- tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/app.manifest
- tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/app.conf
- tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/static/openapi.json
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/app.manifest
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/default/app.conf
- tests/testdata/expected_addons/expected_output_no_global_config/Splunk_TA_UCCExample/app.manifest
- tests/testdata/expected_addons/expected_output_no_global_config/Splunk_TA_UCCExample/default/app.conf
- tests/testdata/test_addons/package_global_config_configuration/package/app.manifest
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/package/app.manifest
- tests/testdata/test_addons/package_no_global_config/package/app.manifest
- tests/unit/testdata/app.conf.minimal.updated
- tests/unit/testdata/app.conf.updated
Jira ref: https://splunk.atlassian.net/browse/ADDON-61384
> fix: app.conf is_configured=false and improve smoke tests

- .github/workflows/build-test-release.yml
- poetry.lock
- pyproject.toml
This PR adds integration of codecov in the pipeline.
> ci: add codecov integration

- get-ucc-ui.sh
UCC UI changes:
* adds test cases for file input component
* adds asterisk near required fields
> feat: update UCC UI to v1.24.0

- .licenserc.yaml
- .pre-commit-config.yaml
- docs/quickstart.md
- splunk_add_on_ucc_framework/commands/import_from_aob.py
- splunk_add_on_ucc_framework/commands/import_from_aob.sh
- splunk_add_on_ucc_framework/commands/imports.py
- splunk_add_on_ucc_framework/main.py
- tests/smoke/test_ucc_import_from_aob.py
- tests/unit/test_main.py
This introduces a new command to import add-on built with AoB (Addon Builder) into the UCC-accepted structure.
> feat: introduce ucc-gen import-from-aob

- example/globalConfig.json
- pytest.ini
- splunk_add_on_ucc_framework/templates/input.template
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/bin/example_input_four.py
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/bin/example_input_one.py
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/bin/example_input_three.py
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/bin/example_input_two.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
Docs: https://dev.splunk.com/enterprise/reference/modinputs/modinputsintrospection/
> fix: use_single_instance=False by default

- example/globalConfig.json
- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/unit/test_install_python_libraries.py
Docs: https://docs.python.org/3/library/subprocess.html#replacing-os-system
Replaces #585
> refactor: use subprocess.call instead of os.system

- docs/index.md
- docs/ucc_related_libraries.md
- mkdocs.yml
This PR creates an initial version of describing other UCC-related libraries.
> docs: initial version of describing solnlib and splunktaucclib

- splunk_add_on_ucc_framework/commands/openapi_generator/ucc_to_oas.py
> fix: openapi.json should not contain disabled property for input creation

- .coveragerc
- example/globalConfig.json
- poetry.lock
- pyproject.toml
- splunk_add_on_ucc_framework/commands/openapi_generator/json_to_object.py
- splunk_add_on_ucc_framework/commands/openapi_generator/ucc_to_oas.py
- splunk_add_on_ucc_framework/commands/rest_builder/builder.py
- splunk_add_on_ucc_framework/commands/rest_builder/endpoint/base.py
- splunk_add_on_ucc_framework/commands/rest_builder/validator_builder.py
- splunk_add_on_ucc_framework/install_python_libraries.py
- splunk_add_on_ucc_framework/rest_map_conf.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/unit/commands/openapi_generator/test_json_to_object.py
- tests/unit/commands/test_init.py
- tests/unit/test_app_manifest.py
- tests/unit/test_global_config.py
- tests/unit/test_install_python_libraries.py
- tests/unit/test_utils.py
- tests/unit/testdata/app.manifest_without_comments.broken
- tests/unit/testdata/valid_config_only_configuration.json
This PR has a fix for not installing libraries twice and improves the coverage across the codebase.
> test: improve coverage across the board

- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/global_config.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/unit/conftest.py
- tests/unit/test_global_config.py
- tests/unit/testdata/valid_config_only_configuration.json
- tests/unit/testdata/valid_config_only_logging.json
This PR gives `global_config.GlobalConfig` class ability to check if OAuth is configured in the `global_config` file.
> refactor: OAuth support for global_config.GlobalConfig

- example/globalConfig.json
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/utils.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
* move get_os_path out to utils
* get rid of PARENT_DIR in build
* move recursive_overwrite to utils 
* move app_manifest read logic to a separate function
> refactor: work on code improvements in build command area

- .github/workflows/build-test-release.yml
The integration does not work as I expected.
> ci: remove codecov

- get-ucc-ui.sh
Related PR: https://github.com/splunk/addonfactory-ucc-base-ui/issues/401
> fix: update UCC UI to v1.27.1

- poetry.lock
Taking some dependency updates from #777
> chore: update some dependencies

- get-ucc-ui.sh
Corresponding UCC UI release: https://github.com/splunk/addonfactory-ucc-base-ui/releases/tag/v1.28.0
> feat: added support for subTitle field in service

- get-ucc-ui.sh
Corresponding PR in the UCC UI: https://github.com/splunk/addonfactory-ucc-base-ui/pull/403
> fix: typo in UCC UI v1.28.0

- .github/workflows/build-test-release.yml
- docs/contributing.md
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/ui/pytest.ini
- tests/ui/test_proxy_page.py
The initial tests taken from Box add-on.
> test: add more UI tests for the proxy page

- get-ucc-ui.sh
Related PR: https://github.com/splunk/addonfactory-ucc-base-ui/issues/429
> feat: update UCC UI to v1.31.0

- tests/ui/test_account_page.py
- tests/ui/test_input_page.py
- tests/ui/test_logging_page.py
Each commit represents one test cleanup.
> test(ui): clean up some of the UI tests

- .github/workflows/build-test-release.yml
This PR actually includes a UCC UI in the released build.
> fix: include UCC UI into UCC during the release step

- docs/uccignore.md
- mkdocs.yml
- pyproject.toml
- splunk_add_on_ucc_framework/commands/build.py
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
Related to #362.
This PR documents `.uccignore` feature.
> docs: document .uccignore feature

- docs/advanced/oauth_support.md
- ui/src/main/webapp/components/BaseFormView.jsx
feat: based on config in globalConfig.json
add possibility to append token_access_type to oauth endpoint
> feat: add optional query param to endpoint

- splunk_add_on_ucc_framework/global_config_validator.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/appserver/static/js/build/globalConfig.json
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/unit/test_global_config_validator.py
- tests/unit/testdata/invalid_config_group_has_duplicate_labels.json
- ui/src/main/webapp/components/BaseFormView.jsx
GitHub Issue - #873
**Before the fix:**
**After the fix:**
> fix(code): fix child keys warning

- splunk_add_on_ucc_framework/global_config_validator.py
- tests/unit/test_global_config_validator.py
- tests/unit/testdata/invalid_config_file_is_encrypted_but_not_required.json
- ui/src/main/webapp/components/BaseFormView.jsx
- ui/src/main/webapp/components/ControlWrapper.jsx
- ui/src/main/webapp/components/FileInputComponent.jsx
- ui/src/main/webapp/components/FileInputComponent.test.tsx
- ui/src/main/webapp/components/FileInputComponent.tsx
- ui/src/main/webapp/constants/constant.ts
- ui/src/main/webapp/constants/fileInputConstant.ts
The same PR as https://github.com/splunk/addonfactory-ucc-base-ui/pull/439.
> feat: file component support file deletion

- tests/unit/test_global_config_validator.py
- tests/unit/testdata/valid_config_deprecated_placeholder_usage.json
> test: fix unit tests after previous PR

- docs/dashboard.md
This PR improves the documentation regarding the dashboard feature.
> docs(dashboard): describe each panel and give an example how to use in globalConfig file

- .github/workflows/build-test-release.yml
This was some leftover code for UI tests (cleaning it up).
> ci: don't rebuild add-on one more time for UI tests

- .github/workflows/build-test-release.yml
- .licenserc.yaml
- scripts/include-rum.sh
- scripts/rum-script.html
> ci: add script for injecting Splunk RUM to test-addon

- ui/tsconfig.json
fixes false positive issues in IDEA
> chore(ui): fix TypeScript types resolution

- .github/CODEOWNERS
Adding Viktor as a codeowner for UI part of the repository.
> chore(codeowners): adjusting ownership for UI changes

- splunk_add_on_ucc_framework/global_config_validator.py
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/unit/test_global_config_validator.py
- tests/unit/testdata/invalid_config_configuration_autoCompleteFields_children_integer_values.json
- tests/unit/testdata/invalid_config_configuration_autoCompleteFields_integer_values.json
> fix: globalConfig validator respects numbers in values in autoCompleteFields

- pyproject.toml
- ui/src/components/ControlWrapper.tsx
Jira ref: https://splunk.atlassian.net/browse/ADDON-67020
Fixes "cancel" button visual issue.
> chore: release v5.34.1

- splunk_add_on_ucc_framework/schema/schema.json
- ui/src/components/EntityModal/EntityModal.test.tsx
- ui/src/components/EntityModal/TestConfig.ts
- ui/src/types/globalConfig/entities.ts
Adding auth_endpoint_token_access_type to schema.json and entity type along with some tests to verify it.
> fix: add tests and auth_access_token to schema

- renovate.json
This PR makes our Renovate's PRs a bit more realistic.
> chore(renovate): add exceptions for UI libraries that are dependent on SUI

- .github/workflows/build-test-release.yml
- .github/workflows/build-ui.yml
- .github/workflows/docs.yml
- poetry.lock
- pyproject.toml
Inspired by #915, taking some dependencies from there and updating them in this PR.
> chore: update some of the dependencies

- docs/contributing.md
> docs: follow up after PRs to develop also run UI tests

- ui/package.json
- ui/yarn.lock
This UI dev dependency is not used.
> chore(deps): remove semantic-release

- docs/contributing.md
This PR adds a development flow for UCC: how to develop, how to release and how to make quick bug fix release.
> docs: update contributing guide with dev flow

- ui/package.json
- ui/yarn.lock
update axios due to follow redirect old version, fossa issue
> fix: update axios along with follow redirect

- renovate.json
> chore(renovate): ignore nodejs engines updates

- docs/dashboard.md
- splunk_add_on_ucc_framework/dashboard.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/data/ui/views/dashboard.xml
- tests/unit/test_dashboard.py
Changes for "Events ingested by sourcetype" panel:
* Change SPL function from avg() to sum()
* Change chart type from line to column
> feat: change avg() to sum() in PANEL_EVENTS_INGESTED_BY_SOURCETYPE_TEMPLATE panel

- splunk_add_on_ucc_framework/templates/input.name.init-template
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/bin/demo_input.py
Change custom exception handler in demo add-on to the one provided by solnlib.
> chore: add log_exception to demo addon

- ui/src/components/CheckboxGroup/checkboxGroup.utils.test.ts
- ui/src/components/CheckboxGroup/checkboxGroup.utils.ts
[ADDON-67906 [UCC] [UI] Enhancement for the checkboxGroup component](https://splunk.atlassian.net/browse/ADDON-67906)
- added unit tests to cover that functionality
> feat(checkboxGroup): correctly parsing values with spaces

- ui/.storybook/main.ts
- ui/.storybook/preview.tsx
- ui/package.json
- ui/src/components/CheckboxGroup/checkboxGroupMocks.ts
- ui/src/mocks/globalConfigMock.ts
- ui/src/public/mockServiceWorker.js
- Fix misconfigured after update msw-storybook-addon 
- POST handler moved from checkbox specific stories to common to handle EntityModal form as well
> chore(msw-addon): fix api mocking for storybook

- ui/.storybook/main.ts
- ui/package.json
- ui/src/components/EntityModal/EntityModal.stories.tsx
- ui/yarn.lock
> chore(package): add @storybook/addon-a11y for accessibility checks

- docs/configurations/index.md
- docs/configurations/proxy.md
- docs/table.md
- mkdocs.yml
Documentation change in order to avoid confusion. Requested in ADDON-61727.
> fix: Add page for proxy configuration

- docs/quickstart.md
This PR updates documentation for quickstart page.
> docs: update quickstart.md

- .github/workflows/storybook-visual.yml
- ui/.Dockerfile
- ui/package.json
- add condition to update screenshots for PRs and check only otherwise
- force docker image to install the latest yarn because we update our deps more frequently than the base image
> test: update screenshots only in PRs

- ui/src/components/BaseFormView.tsx
- ui/src/components/EntityModal/EntityModal.tsx
support of async onSave for custom hooks
https://splunk.atlassian.net/browse/ADDON-62206
> feat: add possibility to use async onSave method

- ui/src/components/EntityPage/EntityPage.tsx
Add async on save for entity page
adding to that one: https://github.com/splunk/addonfactory-ucc-generator/pull/1079/files
> feat: add async on save to entity page

- docs/entity/index.md
- docs/entity/modifyFieldsOnValue.md
- mkdocs.yml
- splunk_add_on_ucc_framework/schema/schema.json
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- ui/src/components/BaseFormTypes.ts
- ui/src/components/BaseFormView.tsx
- ui/src/components/ControlWrapper/ControlWrapper.tsx
- ui/src/components/FormModifications/FormModifications.test.tsx
- ui/src/components/FormModifications/FormModifications.ts
- ui/src/components/FormModifications/TestConfig.ts
- ui/src/components/MarkdownMessage/MarkdownMessage.tsx
- ui/src/components/MarkdownMessage/stories/MarkdownMessage.stories.ts
- ui/src/types/globalConfig/entities.ts
add feature:
https://splunk.atlassian.net/browse/ADDON-67012
> feat: modify fields on value

- ui/src/components/CheckboxGroup/CheckboxGroup.tsx
- ui/src/components/CheckboxGroup/CheckboxRow.tsx
- ui/src/components/CheckboxGroup/StyledComponent.tsx
- ui/src/components/CheckboxGroup/stories/CheckboxGroup.stories.tsx
- ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-base-chromium.png
- ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-create-mode-chromium.png
- ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-input-page-view-chromium.png
- ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-mixed-with-groups-chromium.png
- ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-multiline-chromium.png
- ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-with-single-group-chromium.png
- ui/src/pages/Input/stories/__images__/InputPage-input-page-view-chromium.png
- ui/src/pages/Input/stories/__images__/InputPage-input-tab-view-chromium.png
- removed extra element wrappers
- add data attributes to select input and checkbox by fields
- add better multiline support
> test(CheckboxGroup): add data attributes for easier testing

- docs/custom_ui_extensions/custom_cell.md
- docs/custom_ui_extensions/custom_control.md
- docs/custom_ui_extensions/custom_hook.md
- docs/custom_ui_extensions/custom_menu.md
- docs/custom_ui_extensions/overview.md
- mkdocs.yml
> docs: explain custom ui extension

- tests/ui/test_configuration_page_account_tab.py
- tests/ui/test_input_page.py
This PR extends ui tests set 
Connected to: https://splunk.atlassian.net/browse/ADDON-65714
> test: UI tests extension

- ui/src/components/BaseFormView.tsx
since update of Base Form view to ts ([tag 5.38](https://github.com/splunk/addonfactory-ucc-generator/tree/v5.38.0/ui/src/components)) custom elements do not have current value forwarded, 
problems: edit did not work as expected, as value was missed during rendering process
it fixes issue by adding value in case of custom control element
> fix: custom value passed to component

- docs/inputs/index.md
fix docs reference for custom menu link
> docs: fix reference to custom menu

- poetry.lock
> fix: update idna to 3.7

- splunk_add_on_ucc_framework/global_config_update.py
added schema version update for alert action updates
> fix: add schema version update for alert action

- docs/configurations/logging.md
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/commands/openapi_generator/ucc_to_oas.py
- splunk_add_on_ucc_framework/global_config.py
- splunk_add_on_ucc_framework/global_config_update.py
- splunk_add_on_ucc_framework/global_config_validator.py
- splunk_add_on_ucc_framework/schema/schema.json
- splunk_add_on_ucc_framework/tabs/logging_tab.py
- splunk_add_on_ucc_framework/tabs/tab.py
- tests/smoke/test_ucc_build.py
- tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_settings.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_settings.py
- tests/testdata/test_addons/package_files_conflict_test/globalConfig.json
- tests/testdata/test_addons/package_global_config_configuration/globalConfig.json
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
- tests/testdata/test_addons/package_global_config_only_one_tab/globalConfig.json
- tests/unit/tabs/test_logging_tab.py
- tests/unit/tabs/test_tab.py
- tests/unit/test_global_config.py
- tests/unit/test_global_config_update.py
- tests/unit/testdata/valid_config_logging_tab_not_migrated.json
- tests/unit/testdata/valid_config_only_logging.json
This fixes the problem with `splunk-add-on-for-okta-identity-cloud`
> fix: do not migrate a logging tab when defaultValue is not set

- ui/package.json
- ui/yarn.lock
- Remove `@splunk/react-ui` from resolutions in `package.json` in ui folder.
- Allow minor version updates for `@splunk/react-ui`
> chore: remove splunk ui package resolution

- .github/PULL_REQUEST_TEMPLATE.md
This PR introduces a new PR template.
> ci(governance): add PR template

- tests/unit/test_global_config_validator.py
Fixes unit test step after merge.
N/A
> test: fix unit tests after merge

- renovate.json
- ui/package.json
- ui/yarn.lock
- manually update package.json
- allow renovate to update it automatically
No changes
> chore(deps): update msw-storybook-addon

- .github/workflows/build-test-release.yml
- mkdocs.yml
- tests/ui/conftest.py
- tests/ui/test_alert_actions_page.py
- tests/ui/test_configuration_page.py
- tests/ui/test_configuration_page_account_tab.py
- tests/ui/test_configuration_page_custom_tab.py
- tests/ui/test_configuration_page_logging_tab.py
- tests/ui/test_configuration_page_proxy_tab.py
- tests/ui/test_input_page.py
**Issue number:** ADDON-71787
Adjusting `mkdocs` configuration not to show fixtures etc.
Users will see only the test cases in the documentation.
> docs: show only tests

- ui/.storybook/withSplunkTheme.tsx
- ui/src/pages/EntryPageStyle.js
- ui/src/pages/entry_page.jsx
Extracted styles to avoid recursive imports
Users will enjoy a working storybook
> docs(storybook): fix storybook build

- docs/CHANGELOG.md
> docs: fix changelog title 5.48.1

- .licenserc.yaml
- poetry.lock
- pyproject.toml
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/meta_conf.py
- tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/server.conf
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/alert_actions.conf.spec
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/alert_actions.conf
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/eventtypes.conf
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/server.conf
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/tags.conf
- tests/unit/test_meta_conf.py
- tests/unit/testdata/alert_actions.conf.generated
- tests/unit/testdata/alert_actions.conf.spec.generated
- tests/unit/testdata/app.conf.minimal.updated
- tests/unit/testdata/app.conf.supported_themes
- tests/unit/testdata/app.conf.updated
- tests/unit/testdata/app.conf.updated_not_visible
- tests/unit/testdata/eventtypes.conf.generated
- tests/unit/testdata/server.conf.generated
- tests/unit/testdata/tags.conf.generated
Updating `addonfactory-splunk-conf-parser-lib` library version.
Extra lines at the end of the file would be removed.
> chore(deps): updated addonfactory-splunk-conf-parser-lib lib

- docs/entity/modifyFieldsOnValue.md
- splunk_add_on_ucc_framework/schema/schema.json
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- ui/src/components/BaseFormView/BaseFormTypes.ts
- ui/src/components/BaseFormView/BaseFormView.tsx
- ui/src/components/ControlWrapper/ControlWrapper.tsx
- ui/src/components/FormModifications/FormModifications.ts
- ui/src/types/globalConfig/entities.ts
https://splunk.atlassian.net/browse/ADDON-73241 
Possibility to modify require parameter on front-end
fieldsToModify also supports require property. (only front-end part)
> User right now can modify also required property in other form fields.
> feat: add required as modifiable property

- docs/dashboard.md
**Issue number:[ADDON-72792](https://splunk.atlassian.net/browse/ADDON-72792)**
Update of documentation regarding the monitoring dashboard.
Added information about "all time" issue for overview section.
Added information about new optional parameter `license_usage_source` in the solnlib lib in version 5.2
Better documentation. 
> docs: update of documentation regarding the monitoring dashboard

- .github/workflows/build-test-release.yml
I accidentally merged PR to main instead of develop. This PR backport changes into develop
> chore: merge main into develop

- scripts/quick_start_ui.sh
- scripts/run_splunk.sh
> chore: update splunk image version to 9.3.1

- .coveragerc
- ui/src/components/FileInputComponent/FileInputComponent.test.tsx
**Issue number**: *ADDON-72533*
> Fix flakiness of unit test (FileInputComponent)
> fix the test case so don't affect the user experience
> test: flakiness of unit test (FileInputComponent)

- docs/CHANGELOG.md
> docs: update CHANGELOG.md for 5.51.0

- docs/contributing.md
> docs: update contributing guide (release instructions)

- docs/advanced/oauth_support.md
- docs/entity/index.md
There are 2 warning texts in the documentation that are not rendered correctly. This PR replaces them to another variant that renders properly.
No changes from the UX.
> docs: fix warning panels

- ui/src/types/modules.d.ts
add missing types for Splunk utils
No changes
> refactor: add types for Splunk utils modules

- scripts/quick_start_ui.sh
Previously, old container was not removed in case of conflicting name
No changes
> chore(quick_start_ui.sh): fix container name

- docs/contributing.md
Update syntactically incorrect commands in docs
Enjoyable experience while building TAs with local version of UCC
> docs(contributing): update commands for building TA

- ui/src/pages/Configuration/tests/ConfigurationPage.test.tsx
Add tests to check if network error is actually showing on the page
No changes
> test(ui): check showing network error

- scripts/quick_start_ui.sh
- ui/src/components/table/CustomTableRow.jsx
- ui/src/pages/Configuration/stories/ConfigurationPage.stories.tsx
- ui/src/pages/Configuration/stories/__images__/ConfigurationPage-configuration-view-add-chromium.png
- ui/src/pages/Configuration/stories/globalConfig.json
- ui/src/pages/Input/stories/InputPage.stories.tsx
- ui/src/pages/Input/stories/__images__/InputPage-input-page-expanded-row-chromium.png
- ui/src/pages/Input/stories/__images__/InputPage-input-page-view-add-chromium.png
- ui/src/pages/Input/stories/__images__/InputPage-input-page-view-chromium.png
- ui/src/pages/Input/stories/__images__/InputPage-input-page-view-update-input-chromium.png
- ui/src/pages/Input/stories/globalConfig.json
**Issue number:** ADDON-76446
- add accessible labels to Action Buttons in table (required for testing)
- add new screenshots for configuration and input to show how it is rendered now
No changes (almost)
> test(selectors): add numeric values

- tests/unit/test_global_config_update.py
- tests/unit/testdata/valid_config_input_with_enable_action.json
Added unit test cases for enable action in table inputs
> Added unit test case regarding enable action in `global_config_update.py` file.
> No change in user experience
> tests: added test cases for enable action

- .github/PULL_REQUEST_TEMPLATE.md
- docs/contributing.md
Adding development guidelines to the contributing guide.
N/A
> docs(contributing): add development guidelines

- ui/src/components/table/stories/configMockups.ts
- ui/src/components/table/tests/TableExpansionRow.test.tsx
**Issue number:** ADDON-76309
#1445
Add expected failing tests to reproduce the bug
No changes
> test(TableExpansionRow): add reproduction with stale values for Expansion Row

- .releaserc
- docs/CHANGELOG.md
(cherry picked from commit 020ada0d2b1245157fceebf0ceccb16d6ab7bc19)
PR #1466
Lack of these changes blocks release
> docs(changelog): fix headers consistency (#1466)

- poetry.lock
- pyproject.toml
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/ui/test_configuration_page_account_tab.py
- tests/ui/test_input_page.py
Updating SmartX to 5.3.1 (https://github.com/splunk/addon-factory-smartx-ui-test-library/releases/tag/v5.3.1).
To fix https://github.com/splunk/addonfactory-ucc-generator/actions/runs/12010223758/job/33477076244?pr=1475#annotation:8:123.
2 UI tests were adjusted not to open Splunk's documentation website but only to check that the `href` element is a correct one. This should actually fix the error mentioned above.
N/A
> chore(smartx): update to 5.3.1

- .coveragerc
Bump minimum coverage from 81 to 81.5.
N/A
> chore(coverage): bump from 81 to 81.5

- ui/jest.polyfills.ts
- ui/src/components/DeleteModal/DeleteModal.test.tsx
- ui/src/components/table/tests/TableWrapper.test.tsx
I stumbled to the issue this tests does not render updated values since update function was mocked. So, I am removing the mock to avoid confusions in future
No changes
> test(TableWrapper): remove mocking immutability-helper dep

- README.md
- docs/index.md
- docs/quickstart.md
Minor documentation changes, added a reference to an Example TA.
Improved documentation.
> docs: minor changes

- splunk_add_on_ucc_framework/templates/globalConfig.json.init-template
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/globalConfig.json
**Issue number:** ADDON-76440
Added default validators for api_key and account in `globalConfig.json.template` file 
Added default validator in `globalConfig.json.template` file so that user didn't get warnings in their terminal. For not having validations for their entities.
No change in user experience
> feat: add default validators

- renovate.json
We use react@16, but react-router-dom@7 requires at least react@17 as a peer dependency, so we can't upgrade it until we upgrade react version
No changes
> chore(renovate): disable major updates for react-router-dom

- .addonmatrix
- .github/workflows/build-test-release.yml
Using latest matrix action that does not require `.addonmatrix` file in the root so cleaned up this file as well.
N/A
> ci: update matrix action to v3.0

- ui/.storybook/main.ts
- ui/.storybook/preview.tsx
- Removed autodocs (it did not work anyway)
- Moved toolbar declaration to the Preview object. It was required to split globalTypes and their initial values (initialGlobals)
No changes
> chore(storybook): migrate deprecated toolbar

- .github/workflows/build-test-release.yml
- .releaserc
- update package.json version together with pyproject.toml
- run `npm publish` with dry run. If it fails, it does not fail the build due to ` || true`
- format JSON in .releaserc
No changes 
> ci: npm publish dry run

- ui/src/components/DeleteModal/DeleteModal.tsx
There are some compatibility issues with React 18 and exactly this component. Other class components work fine, so I rewrite it and it works fine.
- Rewritten class component into the functional component
No changes
> refactor(DeleteModal): class component into the functional one

- ui/jest.config.ts
Increase ui jest threshold coverage. Increasing to current coverage percentage. Future improvements shouldn't decrease those values.
```
statements: 66, // => 73
branches: 57, // => 65
functions: 65, // => 73
lines: 66, // => 73
```
N/A
> chore: increase ui jest coverage

- docs/advanced/os-dependent_libraries.md
**Issue number:** ADDON-78048
Document what Python versions are now allowed for OS-dependent libraries feature.
N/A
> docs: update on OS-dependent libraries

- docs/entity/modifyFieldsOnValue.md
Improve docs based on recent question/problem raised.
N/A
> docs: modifications troubleshooting

- ui/src/util/Validator.js
- ui/src/util/tests/validators.test.ts
> test: add validation tests

- .github/workflows/ta-tests.yml
**Issue number:** ADDON-76776
- Add ability to pick splunktaucclib from branch
- Fix manual workflwow to specify a single TA to run
No changes
> ci(ta-tests): run splunktaucclib from branch

- .github/workflows/ta-tests.yml
There is an intermittent issue in CI: https://github.com/splunk/addonfactory-ucc-generator/actions/runs/13695022923/job/38295481156
<details><summary>Logs</summary>
<p>
```plaintext
• Installing threadpool (1.3.2)
StopIteration
at /opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/poetry/puzzle/provider.py:489 in complete_package
485│             except PackageNotFound as e:
486│                 try:
487│                     dependency_package = next(
488│                         DependencyPackage(dependency, pkg)
→ 489│                         for pkg in self.search_for_installed_packages(dependency)
490│                     )
491│                 except StopIteration:
492│                     raise e …
```
> ci(ta-tests): replace pip poetry installation with their script

- .github/PULL_REQUEST_TEMPLATE.md
- docs/contributing.md
**Issue number:** ADDON-78812
The PR template and the Contributing docs are modified with more information about testing and review process.
No changes.
**Demo/meeting:** live meeting during standup on 2025-03-05
> docs: change the PR template and the contibuting guide

- ui/package.json
- ui/src/components/SingleInputComponent/SingleInputComponent.tsx
- ui/src/components/table/tests/CustomTable.test.tsx
- ui/src/components/table/tests/TableExpansionRow.test.tsx
- ui/src/components/table/tests/mocks.ts
- ui/src/pages/Input/stories/InputPage.stories.tsx
- ui/yarn.lock
use old version (4.41.0) of splunk react ui
More info will be working correctly after adding new row.
> fix: more info correctly expands

- ui/src/components/TextAreaComponent/TextAreaComponent.tsx
**Issue number:** ADDON-78814
SUI has deprecated field canClear
https://splunkui.splunk.com/Packages/react-ui/TextArea?section=develop
- Removed canClear
No quick clear button for Text Area
**Before:**
**After:**
> feat(TextArea): remove clear button

- ui/src/components/CustomMenu/CustomMenu.jsx
- ui/src/components/CustomMenu/CustomMenu.tsx
- ui/src/components/CustomMenu/CustomMenuBase.ts
- ui/src/components/CustomMenu/test/CustomMenu.test.tsx
- ui/src/components/CustomMenu/test/mocks/CustomMenuMock.ts
- ui/src/components/CustomMenu/test/mocks/globalConfigMock.ts
- ui/src/components/MenuInput/MenuInput.tsx
- ui/src/publicApi.ts
https://splunk.atlassian.net/browse/ADDON-79405
Custom menu component to typescript
Remains the same.
> refactor: custom menu to ts

- ui/package.json
- ui/yarn.lock
N/A
Resolution due to security issues.
N/A
> chore: resolution http-proxy-middleware "^2.0.9"

- splunk_add_on_ucc_framework/generators/xml_files/create_default_xml.py
- tests/unit/generators/xml_files/test_create_default_xml.py
**Issue number:** ADDON-80103
While generating XML content from `data_ui_generator` we were previously accessing `global_config.meta.get("default_view")` which should be `global_config.meta.get("defaultView")`.
Made the respective changes and also added the test cases to cover all scenario’s.
As the issue is fixed, users can now set their `defaultView` as they require.
> fix: fixed defaultView error

- docs/advanced/oauth_support.md
> docs: Oauth 2.0 client credentials info

- .github/workflows/build-test-release.yml
- docs/commands.md
- poetry.lock
- pyproject.toml
- splunk_add_on_ucc_framework/commands/validate.py
- splunk_add_on_ucc_framework/main.py
- tests/unit/commands/test_validate.py
**Issue number:** ADDON-76818
Introduced a new command `ucc-gen validate`, which will validate the user provided add-on using `splunk-appinspect`. For now, we have only included `cloud` tag while validating add-ons.
Users will now be able to validate their apps and add-ons during development time to ensure that their add-on meets
Splunk's standards and best practices.
`ucc-gen validate --addon-path <path_for_addon>`
> feat: added ucc-gen validate command support

- docs/entity/components.md
> docs: interval docs fix

- splunk_add_on_ucc_framework/generators/conf_files/create_account_conf.py
- splunk_add_on_ucc_framework/generators/conf_files/create_alert_actions_conf.py
- splunk_add_on_ucc_framework/generators/conf_files/create_eventtypes_conf.py
- splunk_add_on_ucc_framework/generators/conf_files/create_restmap_conf.py
- splunk_add_on_ucc_framework/generators/conf_files/create_server_conf.py
- splunk_add_on_ucc_framework/generators/conf_files/create_settings_conf.py
- splunk_add_on_ucc_framework/generators/conf_files/create_tags_conf.py
- splunk_add_on_ucc_framework/generators/html_files/create_alert_actions_html.py
- splunk_add_on_ucc_framework/generators/xml_files/create_configuration_xml.py
- splunk_add_on_ucc_framework/generators/xml_files/create_dashboard_xml.py
- splunk_add_on_ucc_framework/generators/xml_files/create_default_xml.py
- splunk_add_on_ucc_framework/generators/xml_files/create_inputs_xml.py
- splunk_add_on_ucc_framework/generators/xml_files/create_redirect_xml.py
- tests/unit/generators/conf_files/test_create_account_conf_spec.py
- tests/unit/generators/conf_files/test_create_alert_actions_conf.py
- tests/unit/generators/conf_files/test_create_eventypes_conf.py
- tests/unit/generators/conf_files/test_create_restmap_conf.py
- tests/unit/generators/conf_files/test_create_server_conf.py
- tests/unit/generators/conf_files/test_create_tags_conf.py
- tests/unit/generators/html_files/test_create_alert_actions_html.py
- tests/unit/generators/xml_files/test_create_configuration_xml.py
- tests/unit/generators/xml_files/test_create_dashboard_xml.py
- tests/unit/generators/xml_files/test_create_inputs_xml.py
- tests/unit/generators/xml_files/test_create_redirect_xml.py
In `generators` module there were inconsistency in return statements. So instead of returning dict of empty strings, we are returning empty dict.
Because of it, unit test cases are also updated.
No change in User experience.
> refactor: refactored inconsistent code

- tests/ui/test_configuration_page_account_tab.py
- ui/src/components/BaseFormView/BaseFormView.tsx
- ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
- ui/src/components/EntityModal/EntityModal.test.tsx
NA for now
This is how it looks : 
> refactor: update oauth type labels

- .flake8
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/commands/rest_builder/user_defined_rest_handlers.py
- splunk_add_on_ucc_framework/global_config.py
- tests/unit/conftest.py
- tests/unit/generators/conf_files/test_create_restmap_conf.py
- tests/unit/generators/conf_files/test_create_web_conf.py
- tests/unit/test_user_defined_rest_handlers.py
- tests/unit/testdata/valid_config_logging_with_user_defined_handlers.json
`UserDefinedRestHandlers` takes all definitions directly, it allowed to simplify testing a bit and remove some of the public methods used before in this class.
Also refactored `web.conf` and `restmap.conf` tests to do one thing per test.
N/A
> refactor: UserDefinedRestHandlers takes all definitions directly

- .github/workflows/storybook-visual.yml
- ui/jest.polyfills.ts
- ui/package.json
- ui/src/pages/Dashboard/tests/DashBoardPage.test.tsx
- ui/src/pages/Dashboard/tests/DashboardModal.test.tsx
- ui/src/pages/Dashboard/tests/mockMatchMediaForDashboardPage.ts
- ui/yarn.lock
Updating Dashboard libraries and modifying tests accordingly.
There was an issue with the newly added package uPlot in @splunk/dashboard-utils. There is [a function call](https://github.com/leeoniya/uPlot/blob/211f06d6d258833d025952e890a612b254b0a9fb/src/utils.js#L270) where the value window.navigator.language is passed to Intl.NumberFormat constructor. The problem is the headless chromium in Ci sets the value to en-US@posix and it cases the constructor to throw an error. The expected value is en-US. This is fixed by specifying LC_ALL=en_US env variable before starting the storybook.
window.matchMedia polyfill is stolen from the dashboard-framework repository since they also introduced it for running jest tests
N/A
If an …
> test: modifications due to dashboard package update

- tests/testdata/test_addons/package_global_config_everything/package/lib/requirements.txt
> test: specify pyparser version which is supported by python 3.7

- tests/unit/generators/conf_files/test_create_restmap_conf.py
- tests/unit/testdata/valid_config_logging_with_user_defined_handlers.json
Corrected  `valid_config_logging_with_user_defined_handler.json` file.
No change in user experience.
> test: fix `valid_config_logging_with_user_defined_handler.json`

- docs/options/rest_handlers.md
Corrected the documentation for `Rest_handlers` that are not generated by UCC, based on the definitions in `schema.json`.
No change in user experience.
> docs: fix rest_handlers documentation

- .github/workflows/build-test-release.yml
- splunk_add_on_ucc_framework/data_ui_generator.py
> refactor: replace general xml.etree import with specific modules

- splunk_add_on_ucc_framework/global_config_update.py
- splunk_add_on_ucc_framework/global_config_validator.py
- tests/unit/test_global_config_update.py
- tests/unit/test_global_config_validator.py
If a globalConfig has placeholder present, the build process exits, but while validating it.
No change for user, the build would still stop if globalConfig has `placeholder` present.
> chore: update validation of placeholder usage

- splunk_add_on_ucc_framework/generators/conf_files/create_alert_actions_conf.py
- splunk_add_on_ucc_framework/generators/python_files/create_custom_command_python.py
- tests/unit/generators/conf_files/test_create_alert_actions_conf.py
- tests/unit/generators/conf_files/test_create_inputs_conf.py
- tests/unit/generators/conf_files/test_create_settings_conf.py
- tests/unit/generators/python_files/test_create_custom_command_python.py
- tests/unit/generators/test_file_generator.py
- tests/unit/generators/xml_files/test_create_default_xml.py
- tests/unit/testdata/valid_config_all_alerts.json
**Issue number:** ADDON-79015
Added unit test cases for the generator's module to achieve `100% test coverage`.
No change in user experience.
> test: 100% unit test coverage for generators

- ui/src/components/table/tests/CustomTableCell.test.tsx
Wait for console log to be print out. (without wait the vitest rarely is printing it in next test and triggering console error issue.
N/A. 
> chore: wait for corret console error in test

- splunk_add_on_ucc_framework/global_config_update.py
> chore: fix python linter after oauth entity removal

- docs/commands.md
- docs/custom_ui_extensions/context/custom_project_init.md
- docs/custom_ui_extensions/context/custom_test_ui_command.md
- docs/custom_ui_extensions/context/overview.md
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/main.py
- tests/unit/test_main.py
https://splunk.atlassian.net/browse/ADDON-82962
Custom UI can be build from ucc-gen build after adding --build-custom-ui flag
Custom Ui integrated into ucc-gen build.
> feat: build ui from ucc-gen build

- splunk_add_on_ucc_framework/global_config_validator.py
- tests/testdata/test_addons/package_global_config_configuration/package/bin/someFile.py
- tests/unit/test_check_globalConfig.py
- tests/unit/test_global_config_validator.py
- tests/unit/testdata/invalid_config_with_user_defined_rest_handlers.json
**Issue number:** ADDON-82908
Added a check in `global_config_validator.py` for existence of python scripts mentioned in user-defined handler.
Add-on build would fail if python script mentioned under `options/restHandlers` is not present in add-ons bin directory.
> feat: add check for existence of python scripts in user-defined handler
