splunk/addonfactory-ucc-generator

- splunk_add_on_ucc_framework/__init__.py
- Added Support to generate Addon without input page with old schema(schemaVersion<0.0.1) of globalConfig.json
[jira link](https://jira.splunk.com/browse/ADDON-30463)
> ADDON-30463 handle the case: Add-on with no inputs with old schema.

- splunk_add_on_ucc_framework/__init__.py
When using pip from path in some cases pip3 may be used when pip is the install command switch to python -m pip syntax to ensure correct build
> Ensure corrrect python pip version is used

- splunk_add_on_ucc_framework/UCC-UI-lib/package/appserver/static/js/util/promptMsgController.js
Jira Link:  https://jira.splunk.com/browse/SPL-196891   
- Updated regex for error message parsing to display proper message on UI.
There is an additional message format supported in Splunk version 8.1.2011 onwards:
`Unexpected error "<class 'splunktaucclib.rest_handler.error.RestError'>" from python handler: "REST Error [400]: Bad Request -- Account authentication failed. Please check your credentials and try again". See splunkd.log/python.log for more details.`
> SPL-196891: Updated regex for error message parsing

- .circleci/config.yml
- splunk_add_on_ucc_framework/__init__.py
- In the latest pip version the build was not generated for MSCS due to `ERROR: ResolutionImpossible:` for some modules s therefore adding legacy resolver param in the installation command.
> Adding legacy resolver param for pip

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/CheckBoxComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/RadioComponent.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/TextComponent.jsx
[ADDON-34289](https://jira.splunk.com/browse/ADDON-34289)
Added Text, Radio and CheckBox components
> ADDON-34289: Added Text, Radio and CheckBox components

- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/Table.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableExpansionRow.js
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableFilter.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableStyle.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/components/table/TableWrapper.jsx
- splunk_add_on_ucc_framework/ucc_ui_lib/src/main/webapp/pages/Input/InputPage.jsx
JIRA Ticket: https://jira.splunk.com/browse/ADDON-34277
Filter functionality is working in the table. For that, we have created a **TableFilter** component and a filter will also be performed on **input type** as well.
**Note:**
For this PR we are passing the data to the component using props only, in the upcoming PR we will be implementing React context API to pass the data to the child component.
> ADDON-34277: Implemented filter functionality in the table component

- .circleci/config.yml
- .semgrepignore
* The issue with the semgrep agent is fixed by upgrading the resource class to large.
* For Semgrep scanning, have raised an issue at https://github.com/returntocorp/semgrep/issues/2784.
* Removed the `js` folder from the [.semgrepignore](https://github.com/splunk/addonfactory-ucc-generator/blob/main/.semgrepignore) file as the issue is covered in this PR
> test: fix the issue with semgrep-agent

- splunk_add_on_ucc_framework/UCC-UI-lib/build_dev.py
- splunk_add_on_ucc_framework/__init__.py
parameterized the input template.  If nothing is specified in globalConfig.json it will default to the original value of "input.template", but if a  "template":"template_name" is supplied, that one will be used.
> feat(Parameterize Input Template): Provide a method to pass in an input template to use

- splunk_add_on_ucc_framework/uccrestbuilder/global_config.py
Updated global_config.py to append TA's directory (schema.product) rather than schema.namespace to os.path.  This will support cases where the directory name (schema.product) is different than the schema.namespace.  This is only used in the generation of import_declare_test.py.
> feat(Append TA directory to os.path): Append TA directory name to os.path rather than namespace

- poetry.lock
- pyproject.toml
- splunk_add_on_ucc_framework/__init__.py
Adds UCC config validation against a predefined JSON schema.
Reason: improve developer experience while creating add on for Splunk. This change should avoid unnecessary builds if config is not correct. For example, error when specifying too long label currently is only visible after installing a TA in Splunk which takes time. This change makes it visible immediately.
Other improvements to consider in the future:
* fail validation if an input contains unsupported option (i.e. "blackList", which was changed to "denyList")
* test case for correct and incorrect configurations
cc: @ricardom-splunk
> feat: validate JSON configuration before generating build

- splunk_add_on_ucc_framework/__init__.py
- Added check for oauth_state_enabled entity and added necessary compatibility steps
- Added checks for onChange and onLoad options
Jira Link : https://jira.splunk.com/browse/ADDON-36748
> Addon 36748 update ucc gen for globalconfig schema changes in version 0.0.2

- docs/Makefile
- docs/conf.py
- docs/how_to_use.rst
- docs/index.rst
- docs/make.bat
- docs/overview.rst
- docs/troubleshooting.rst
- poetry.lock
- pyproject.toml
I've added Sphinx, sphinx-rtd-theme as a requirements to the poetry.
This is an initial version of the docs. I used a README.md as a baseline and reorganised it in Sphinx docs (not adding a lot of new information). It is not yet integrated with readthedocs, but that can be one of next steps when we will be happy with the docs themselves.
What you need to do to see the docs:
* `poetry install`
* `cd docs`
* `make html`
* `open _build/html/index.html`
You should see the same page from the screenshot.
> docs: initial

- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/logger.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/metric_util.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/monitor.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/number_metric_collector.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/__init__.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_base.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_conf_gen.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_helper.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_html_gen.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_merge.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_py_gen.py
- splunk_add_on_ucc_framework/start_alert_build.py
- splunk_add_on_ucc_framework/uccrestbuilder/__init__.py
- splunk_add_on_ucc_framework/uccrestbuilder/builder.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/base.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/datainput.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/field.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/multiple_model.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/oauth_model.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/single_model.py
- splunk_add_on_ucc_framework/uccrestbuilder/global_config.py
- splunk_add_on_ucc_framework/uccrestbuilder/rest_conf.py
This PR was mainly generated by 2to3 tool.
One manual change in splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_conf_gen.py to remove duplicate brackets.
> chore: remove Python 2 related code

- .circleci/config.yml
Supports unit testing in CI.
For now, one line local run of unit tests is not supported as it requires Splunk UCC UI to be downloaded.
You can run unit tests using CircleCI local executor, more details here: https://circleci.com/docs/2.0/local-cli/
> test: add CI support for unit tests

- splunk_add_on_ucc_framework/__init__.py
Checked locally, works fine with and without `ta-version`.
When specifying a `ta-version` argument, for example: `ucc-gen --ta-version=3.0.0`, it will create a `VERSION` file with the following content:
```
3.0.0
3.0.0
```
> fix: quick fix for ta-version argument

- pytest.ini
`tests/data` tests are flaky due to `-n 10` in `pytest.ini`, they are trying to get contents from `globalConfig.json` which may be not in stable state.
Examples:
* https://github.com/splunk/addonfactory-ucc-generator/runs/2783628522
* https://github.com/splunk/addonfactory-ucc-generator/runs/2775867028
> test: fix flaky unit tests

- poetry.lock
- pyproject.toml
This PR bumps Splunk libraries (`solnlib`, `splunktalib` and `splunktaucclib`) to the latest versions and fixes snyk issue.
> fix: update Splunk libraries to latest versions

- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/conf_parser.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/logger.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/event_writer.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/memory_event_writer.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/metric_aggregator.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/metric_util.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/monitor.py
- splunk_add_on_ucc_framework/alert_utils/alert_utils_common/metric_collector/number_metric_collector.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/__init__.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_base.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_conf_gen.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_helper.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_html_gen.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_merge.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_py_gen.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_template.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/cim_actions.py
- splunk_add_on_ucc_framework/normalize.py
- splunk_add_on_ucc_framework/start_alert_build.py
- splunk_add_on_ucc_framework/uccrestbuilder/__init__.py
- splunk_add_on_ucc_framework/uccrestbuilder/builder.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/base.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/field.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/oauth_model.py
- splunk_add_on_ucc_framework/uccrestbuilder/endpoint/single_model.py
- splunk_add_on_ucc_framework/uccrestbuilder/global_config.py
- splunk_add_on_ucc_framework/uccrestbuilder/rest_conf.py
- tests/conftest.py
- tests/data/test_ucc_generate.py
First commit is just `isort .`, second commit is deleting unused imports and third commit is making CI actually green by fixing CI's isort.
> refactor: apply isort and delete unused imports after

- .ucc-ui-version
[ADDON-38581](https://jira.splunk.com/browse/ADDON-38581): fallback to latest form state if resthandler skips some table fields from response
> fix: update ucc ui version to 1.7.7

- splunk_add_on_ucc_framework/__init__.py
- tests/unit/helpers.py
- tests/unit/test_config_file_update.py
- tests/unit/testdata/config_with_biased_terms.json
Add tests to verify that updating biased terms in globalConfig.json is working as expected.
> refactor: extract copy-pasted code into a separate function

- poetry.lock
- pyproject.toml
`reuse`, `Sphinx` and `sphinx-rtd-theme` are not used in the final package.
`Sphinx` and `sphinx-rtd-theme` are used for the documentation purposes, there is a PR (https://github.com/splunk/addonfactory-ucc-generator/pull/244) that tries to add those dependencies to `docs` folder, but facing issue (https://github.com/splunk/addonfactory-ucc-generator/runs/2934974188).
> fix: remove unnecessary dependencies

- splunk_add_on_ucc_framework/templates/README.md
If you run `grep -rn 'input_with_helper' .` - it returns nothing.
> chore: delete unused file

- .ucc-ui-version
Bug Fixes:
* default to `basic` oauth_type if `undefined` to handle upgrade scenario for some add-ons ([c7373eb](https://github.com/splunk/addonfactory-ucc-base-ui/commit/c7373eb02b62c656c6052ae4a7f8de2fc54055f2)) [[ADDON-39022](https://jira.splunk.com/browse/ADDON-39022)]
* skip `null` value fields from displaying in table expansion row ([b69f7aa](https://github.com/splunk/addonfactory-ucc-base-ui/commit/b69f7aa2aa7a8c1a3cc8903560872a650785843e)) [[ADDON-39037](https://jira.splunk.com/browse/ADDON-39037)]
> fix: update UCC UI version to 1.8.1

- .ucc-ui-version
* pass `count` query param in rest to overcome default thirty records limit ([8591f1c](https://github.com/splunk/addonfactory-ucc-base-ui/commit/8591f1c453929b6394f153770ea2f4d18c1a0feb)) [[ADDON-39044](https://jira.splunk.com/browse/ADDON-39044)]
> fix: update ucc ui version to 1.8.2

- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/app_manifest.py
- tests/unit/helpers.py
- tests/unit/test_app_manifest.py
- tests/unit/test_config_file_update.py
- tests/unit/test_config_validation.py
- tests/unit/testdata/app.manifest
- tests/unit/testdata/app.manifest_with_comments
- tests/unit/testdata/app.manifest_with_comments_written
- tests/unit/testdata/app.manifest_with_unsupported_comments
- tests/unit/testdata/app.manifest_written
Lines that start with "#" are supported. Some of the app.manifest files have comments.
Appinspect tool does not fail if app.manifest contains comments. Exact lines of code from appinspect: https://github.com/splunk/appinspect/blob/fabd1387cf41e087edd86fb7f28e2f9e69a1467c/splunk_appinspect/checks/check_support_and_installation_standards.py#L169-L180
> feat: support app.manifest file with comments

- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_py_gen.py
- splunk_add_on_ucc_framework/modular_alert_builder/build_core/arf_template/alert_action.py.template
`lib_name` variable was not used before in `splunk_add_on_ucc_framework/modular_alert_builder/build_core/arf_template/alert_action.py.template` template, but was provided from the Python side.
This caused an `ImportError` for newly generated add-on.
Thanks to @guilhemmarchand for spotting this one.
> fix: broken import after modular alert code generation

- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/global_config_validator.py
- tests/unit/test_config_validation.py
- tests/unit/testdata/invalid_config_no_name_field_in_configuration_tab_table.json
Before this fix - `ucc-gen` generated add-on which did not work in Splunk.
Thanks to @guilhemmarchand for spotting this one.
> fix: validate that a configuration tab with table has field "name"

- splunk_add_on_ucc_framework/modular_alert_builder/build_core/alert_actions_merge.py
`conf_parser.remove_stanza` does not accept second parameter.
> fix: remove non-valid Python code

- .github/workflows/build-test-release.yml
- .github/workflows/exclude-patterns.txt
Those are not used at the moment, so we do not need to keep them in the repository.
> chore: delete review-secrets step

- poetry.lock
- pyproject.toml
Having "*" in pyproject.toml for dunamai leads to installation
of the latest version after running `poetry build`. Lock file is
ignored in this case.
And in case of new dunamai release the new version will be installed
which can break everything.
Related issue: https://github.com/python-poetry/poetry/issues/1307
> fix: dump dunamai to 1.5.5 version

- splunk_add_on_ucc_framework/__init__.py
The jsonschema is not working if we delete the metadata files.
```
File "import_declare_test.py", line 12, in <module>
from jsonschema import validate
File "/opt/splunk2/etc/apps/Splunk_TA_salesforce/lib/jsonschema/__init__.py", line 34, in <module>
__version__ = metadata.version("jsonschema")
File "/opt/splunk2/etc/apps/Splunk_TA_salesforce/lib/importlib_metadata/__init__.py", line 957, in version
return distribution(distribution_name).version
File "/opt/splunk2/etc/apps/Splunk_TA_salesforce/lib/importlib_metadata/__init__.py", line 930, in distribution
return Distribution.from_name(distribution_name)
File "/opt/splunk2/etc/apps/Splunk_TA_salesforce/lib/importlib_metadata/__init__.py", line 524, in from_name
raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No …
```
> fix: Dont remove  jsonschema metadata files

- .ucc-ui-version
- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/uccrestbuilder/global_config.py
- tests/data/package_global_config_configuration/globalConfig.json
- tests/data/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/unit/test_config_file_update.py
`apiVersion` from globalConfig is not used and is already marked as optional in UCC UI repository (https://github.com/splunk/addonfactory-ucc-base-ui/pull/57)
> feat: delete `apiVersion` from globalConfig.json and bump schemaVersion

- pyproject.toml
`install_requirements` function is not in the code anymore.
> chore: remove script which is not relevant anymore

- splunk_add_on_ucc_framework/__init__.py
defusedxml.cElementTree is deprecated
```
splunk_add_on_ucc_framework/__init__.py:29
/Users/arys/src/addonfactory-ucc-generator/splunk_add_on_ucc_framework/__init__.py:29: DeprecationWarning: defusedxml.cElementTree is deprecated, import from defusedxml.ElementTree instead.
from defusedxml import cElementTree as defused_et
```
> refactor: cElementTree is deprecated

- .github/workflows/build-test-release.yml
This PR adds `pre-commit` step to CI and removes Github's `super-linter` step.
Reasons:
1. `pre-commit` is faster (at least 2 times, even with slim `super-linter` Docker image)
2. No need to keep 2 configurations (for `pre-commit` and for `super-linter`)
3. `pre-commit` is easier to run locally
4. This repository mostly has Python files and `pre-commit` should be sufficient.
> ci: add pre-commit step

- splunk_add_on_ucc_framework/uccrestbuilder/rest_conf.py
- tests/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/web.conf
- tests/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/default/web.conf
This commit removes generation of
```
[expose:_splunkd_data]
pattern = data/*
methods = GET
```
for `web.conf`.
Closes #303.
> fix: remove generation of `expose:_splunkd_data` stanza in web.conf

- .ucc-ui-version
* resolve missed `type` param for custom input row feature ([#84](https://github.com/splunk/addonfactory-ucc-base-ui/issues/84)) ([6bc9e13](https://github.com/splunk/addonfactory-ucc-base-ui/commit/6bc9e138568a305521f236ada96e16b33438b033))
> fix: update ucc ui version to 1.9.1

- poetry.lock
- pyproject.toml
- tests/unit/test_alert_actions_conf_gen.py
- tests/unit/test_alert_actions_html_gen.py
- tests/unit/test_alert_actions_py_gen.py
- tests/unit/test_app_conf.py
- tests/unit/test_app_manifest.py
- tests/unit/test_config_file_update.py
- tests/unit/test_config_validation.py
- tests/unit/test_meta_conf.py
- tests/unit/test_uccrestbuilder.py
This allows to remove a "parameterized" dev dependency because we can use "@pytest.mark.parametrize" instead.
> test: move all tests to pytest

- .ucc-ui-version
This version of UCC UI adds a dependencies.txt file under appserver/static/js
with all the JS dependencies included in the add-on.
More info: https://github.com/splunk/addonfactory-ucc-generator/issues/422
> feat: new version of UCC UI

- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/global_config_update.py
- tests/unit/test_global_config_update.py
This PR moves globalConfig.json automatic updates logic to a separate file and remove another ~150 lines from `__init__.py` file.
> refactor: move globalConfig.json update logic to a separate file

- .ucc-ui-version
- get-ucc-ui.sh
- poetry.lock
- pyproject.toml
- splunk_add_on_ucc_framework/commands/build.py
- tests/data/test_ucc_generate.py
- tests/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/data/ui/nav/default.xml
defusedxml library was only used in 1 place which was refactored to remove the dependency by introducing a new file in the UCC UI library and making some manipulations in the file system during the build process.
> refactor: remove dependency on defusedxml

- .github/workflows/build-test-release.yml
People seems to be running `ucc-gen` not only on Python 3.7, so bringing in more tests for those versions as well.
> ci: add 3 more Python versions to unit tests

- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/unit/test_install_python_libraries.py
If an add-on has globalConfig.json, it means that it has UI, so splunktaucclib should be at least included to the
package/lib/requirements.txt (by default). In case there is no such dependency, the add-on will not be built.
The same as #529, there was an issue with rebasing that PR.
> feat: add validation for the splunktaucclib to be included

- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/main.py
- tests/data/package_global_config_configuration/globalConfig.json
- tests/data/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/data/test_ucc_generate.py
- tests/unit/helpers.py
- tests/unit/test_main.py
Updated code to handle when the config param is provided while invoking the `ucc-gen` command. 
Added a test case for the same.
> fix(code): ADDON-57703 handle globalConfig flag

- docs/how_to_use.md
- example/globalConfig.json
- splunk_add_on_ucc_framework/main.py
- tests/unit/test_main.py
This is not a breaking change.
This PR introduces a subcommand `build`. The effect from running `ucc-gen` is the same as from running `ucc-gen build`, but running `ucc-gen` without a subcommand will be deprecated in the future releases.
> refactor: introduce build subcommand

- .github/dependabot.yml
The previous commit I squashed had "ci skip" in it, that's why GitHub decided to skip the whole pipeline.
> feat: trigger v5.20.0 release

- example/globalConfig.json
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/commands/rest_builder/global_config_builder_schema.py
- splunk_add_on_ucc_framework/global_config.py
- splunk_add_on_ucc_framework/global_config_update.py
- splunk_add_on_ucc_framework/global_config_validator.py
- tests/testdata/test_addons/package_global_config_configuration/globalConfig.json
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/unit/test_global_config.py
- tests/unit/test_global_config_update.py
- tests/unit/test_global_config_validator.py
This PR introduces a new class for handling globalConfig file which is reused across some part of the codebase as part of this PR. I did not touch code for generating alerts, but a goal is to reuse it across 100% of the codebase.
No breaking changes are expected as it is only an internal refactoring.
> refactor: introduce and reuse GlobalConfig class to manage globalConfig file

- example/globalConfig.json
- splunk_add_on_ucc_framework/commands/rest_builder/builder.py
- splunk_add_on_ucc_framework/commands/rest_builder/endpoint/base.py
- splunk_add_on_ucc_framework/commands/rest_builder/endpoint/field.py
- tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/default/splunk_ta_uccexample_settings.conf
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/default/splunk_ta_uccexample_settings.conf
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
`ucc-gen` will now generate the default values for the `splunk_ta_<add-on-name>_settings.conf` file. For example, if you have a logging tab and it is "INFO" by default, it will be generated right now.
The UI already shows the default value from the globalConfig, the .conf part was missing. It is important when you want to get your add-on setting via API (with recent OpenAPI file implementation). If you don't set anything in the `.conf` file, the API response will not contain the default value, if the default value is set in the `.conf` file, API will return the default value, so there is no inconsistency anymore.
> feat: generate default values in .conf files

- example/globalConfig.json
- splunk_add_on_ucc_framework/commands/init.py
- splunk_add_on_ucc_framework/commands/init_template/{{cookiecutter.addon_name}}/package/default/{{cookiecutter.addon_name}}_settings.conf
- splunk_add_on_ucc_framework/main.py
- tests/smoke/test_ucc_init.py
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/globalConfig.json
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/app.manifest
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/bin/demo_input.py
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/default/app.conf
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/default/demo_addon_for_splunk_settings.conf
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
Now we generate proper `<addon-name>_settings.conf` file in the output folder for the add-on, so no need to keep it generated by default using `ucc-gen init` command.
The autogenerated `<addon-name>_settings.conf` file in the default folder creates more confusion if you want to continue adding more settings in the globalConfig file, the changes will not be reflected in the `package/default` folder.
> fix: remove <add-on-name>_settings.conf from cookicutter for ucc-gen init

- example/globalConfig.json
- tests/smoke/helpers.py
- tests/smoke/test_ucc_build.py
- tests/smoke/test_ucc_init.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
Extract file content comparison logic into a separate helper module to be reused in `test_ucc_build.py` and `test_ucc_init.py`.
> test: refactor file content comparison logic

- splunk_add_on_ucc_framework/commands/openapi_generator/ucc_to_oas.py
- tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/static/openapi.json
The initial assumption was just too specific about the tabs that need a separate endpoint. The current approach is a correct one.
> fix: config endpoint addresses

- example/globalConfig.json
- splunk_add_on_ucc_framework/__init__.py
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/main.py
- tests/smoke/test_ucc_build.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/unit/test_main.py
This is a breaking change for the Add-on Builder, because it directly uses `ucc-gen` library to build the add-ons. I am not going to release it as a breaking change for everyone, because it is not a breaking change for the users of the `ucc-gen`.
> fix: remove build function from init file

- .github/workflows/build-test-release.yml
I made a rerun to see how cache works and it saves ~30 seconds on each job which uses the same version of Python.
> ci: introduce cache to setup-python job

- .github/workflows/build-test-release.yml
Today we released a new version of `splunk/appinspect-cli-action` (https://github.com/splunk/appinspect-cli-action/releases/tag/v1.7.0).
> ci: update splunk/appinspect-cli-action to v1.7

- splunk_add_on_ucc_framework/main.py
I've been trying to write a test to validate that we are actually logging a warning message, but it seems that using `DefaultSubcommandArgumentParser` instead of just `argparse.ArgumentParser` changes the default behaviour of the pytest itself.
> chore: warn that running just ucc-gen will be deprecated

- .github/CODEOWNERS
Hubert is the best contact if something changes in the UCC OpenAPI.
> chore: Hubert is a codeowner for the OpenAPI

- .fossa.yml
Those requirement files should not be scanned by FOSSA.
> chore: ignore some test paths for fossa

- splunk_add_on_ucc_framework/__init__.py
Having time in the console output is not useful.
> refactor: remove time from logs

- example/globalConfig.json
- splunk_add_on_ucc_framework/commands/rest_builder/global_config_post_processor.py
- tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/import_declare_test.py
- tests/testdata/expected_addons/expected_output_global_config_inputs_configuration_alerts/Splunk_TA_UCCExample/bin/import_declare_test.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
The add-on should use libraries packaged with it first and only then try to use libraries provided by Splunk (one of the cases of such a library is `urllib3` which can be packaged with an add-on and it available from Splunk's Python).
> fix: change the order in the sys.path in import_declare_test

- splunk_add_on_ucc_framework/commands/init_template/{{cookiecutter.addon_name}}/globalConfig.json
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/globalConfig.json
There is a small inaccuracy in the new template generated by `ucc-init`.
> fix help text for generated account

- example/globalConfig.json
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/exceptions.py
- splunk_add_on_ucc_framework/utils.py
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/unit/test_utils.py
Instead of showing a traceback, show an error message in logs and suggest users a solution.
> chore: don't show traceback when not a git repo

- docs/quickstart.md
- example/package/app.manifest
- splunk_add_on_ucc_framework/app_manifest.py
- splunk_add_on_ucc_framework/commands/build.py
- tests/testdata/test_addons/package_global_config_configuration/package/app.manifest
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/globalConfig.json
- tests/testdata/test_addons/package_global_config_inputs_configuration_alerts/package/app.manifest
- tests/testdata/test_addons/package_no_global_config/package/app.manifest
- tests/unit/conftest.py
- tests/unit/test_app_manifest.py
- tests/unit/testdata/app.manifest_incorrect_schema_version
- tests/unit/testdata/app.manifest_written
Docs link: https://dev.splunk.com/enterprise/reference/packagingtoolkit/pkgtoolkitappmanifest/#JSON-schema-200
`schemaVersion`, `targetWorkloads` and `supportedDeployments` keys are now being validated.
> feat: app.manifest is being validated now according to the docs

- splunk_add_on_ucc_framework/utils.py
- tests/unit/test_utils.py
sometimes developers prefer a certain, non alphabetic structure to their definition. generally, we should not modify the globalConfig during the build in my opinion. It is unexpected by the developer
> fix: don't sort yaml as part of the dump

- poetry.lock
- pyproject.toml
Release a fix for https://github.com/splunk/addonfactory-ucc-generator/security/dependabot/5.
> fix: require requests 2.31.0 and urllib3 < 2

- .releaserc
`docs` job is not running then and we could get an outdated version of the docs.
> ci: don't skip pipeline on bot commit

- splunk_add_on_ucc_framework/commands/init_template/{{cookiecutter.addon_name}}/package/bin/{{cookiecutter.addon_input_name}}.py
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/bin/demo_input.py
This PR makes an adjustment to the template of the modular input for the `ucc-gen init` command.
> fix: change modular input template according to globalConfig file

- renovate.json
Splunk add-ons only support urllib3 < 2 as of now, so configuring renovate not to send updates for urllib3 >= 2.
> chore: pin urllib3 to <2 for renovate

- .github/workflows/build-test-release.yml
- splunk_add_on_ucc_framework/commands/build.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/example_input_four.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/example_input_one.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/example_input_three.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/example_input_two.py
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
This is a regression from v5.24.0 when use_single_instance parameter value was changed from true to false.
Not to have such an issue again - we are going to run at least all UI tests for PR to main / push to main or if the label is set. Also, we will need to have some quicker tests to figure out if something is wrong.
> fix: input.template should not render interval field

- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/unit/test_install_python_libraries.py
With the latest pip version, the build started failing because the pip update command is not
deterministic. Since this potentially broke existing pipelines, even though ucc-gen was not  updated
#808
> fix: resolve failing ucc-gen by pinning pip version

- splunk_add_on_ucc_framework/app_conf.py
- splunk_add_on_ucc_framework/commands/build.py
- tests/testdata/test_addons/package_global_config_configuration/package/default/app.conf
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/unit/test_app_conf.py
- tests/unit/testdata/app.conf.updated_not_visible
So called `.conf`-only add-ons should not be visible in the UI.
> fix: add-on without globalConfig file should not be visible

- docs/quickstart.md
- splunk_add_on_ucc_framework/app_manifest.py
- splunk_add_on_ucc_framework/commands/package.py
- splunk_add_on_ucc_framework/main.py
- tests/smoke/test_ucc_package.py
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/unit/test_app_manifest.py
- tests/unit/test_main.py
This is a very first iteration on introducing `ucc-gen package` command. This command packages a built add-on in the same way as `slim` (`splunk-packaging-toolkit`) does.
This command does not support:
* `.slimignore` file
* [dependencies section](https://dev.splunk.com/enterprise/docs/releaseapps/packageapps/packagingtoolkit/#Dependencies-section)
This command can be used for simple add-on where mentioned above limitations can be ignored.
> feat: introduce package command

- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/exceptions.py
- tests/unit/commands/test_build.py
When running `ucc-gen build` it is important to know which Python executable is used (this already exists) but it does not print the version of the executable.
This PR introduces a new log statement and a call to receive the Python version of the executable in use.
> Add selected python version to build output

- docs/entity/components.md
- get-ucc-ui.sh
- splunk_add_on_ucc_framework/global_config_validator.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/inputs.conf.spec
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/example_input_two.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_example_input_two.py
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/unit/test_global_config_validator.py
- tests/unit/testdata/invalid_config_checkbox_groups_duplicate_field_in_options_groups.json
- tests/unit/testdata/invalid_config_checkbox_groups_duplicate_fields_in_options_rows.json
- tests/unit/testdata/invalid_config_checkbox_groups_undefined_field_used_in_groups.json
- tests/unit/testdata/invalid_config_inputs_entity_duplicates.json
- tests/unit/testdata/openapi.json.generated
- tests/unit/testdata/valid_config.json
This PR updates UCC UI to the v1.32.0 which includes this [PR](https://github.com/splunk/addonfactory-ucc-base-ui/pull/438).
This allows us to define a new `checkboxGroup` (see PR's description) to be used for the Inputs page.
> feat: update UCC UI to v1.32.0

- .github/workflows/build-test-release.yml
This PR has a separate step to build the test add-on for UI tests and now it will be uploaded as an artefact for quick local testing purposes. Also we use `dorny/test-reporter` to have a better view on run tests.
> ci: upload built add-on as an artifact

- .github/workflows/build-test-release.yml
Fixes https://github.com/splunk/addonfactory-ucc-generator/actions/runs/6380223274/job/17314260563?pr=854
> ci: fix dorny/test-reporter permissions

- run_splunk.sh
- tests/ui/test_alert_actions_page.py
Using `SPLUNK_DISABLE_POPUPS` env variable to control popups, setting it to `true` so we don't need to have workaround code to bypass those.
Check out docs here: https://github.com/splunk/splunk-ansible/blob/186c95b84d82f9201e036388c716d466d083ae37/docs/ADVANCED.md?plain=1#L101
> test(ui): use SPLUNK_DISABLE_POPUPS and remove workarounds

- .github/workflows/build-test-release.yml
- .releaserc
- docs/entity/validators.md
- docs/index.md
- docs/quickstart.md
- splunk_add_on_ucc_framework/global_config_validator.py
We merged 300+ commits as part of the migration of UCC UI into this repository and as a side effect we made a release because of the commit messages used in those 300+ commits. The entire release was not successful as we hit the GitHub's quota and we were not able to add a comment to each PR.
This PR sets `successComment` to false for "@semantic-release/github" which does not add a comment to every PR involved in the release (300+).
This PR also cleans up references to the UCC UI repository.
> ci: fix release

- .github/workflows/build-test-release.yml
This way we will save some GitHub resources by not running a lot of jobs in the same time for the same PR.
> ci: use concurrency to cancel previous jobs [ci skip]

- .github/workflows/build-test-release.yml
- NOTICE
- docs/CHANGELOG.md
- pyproject.toml
- splunk_add_on_ucc_framework/__init__.py
This was validated for the develop branch, the package was successfully released to PyPI (https://pypi.org/project/splunk-add-on-ucc-framework/5.31.1b1/#files).
> fix: include UCC UI into UCC during the release step

- pyproject.toml
- splunk_add_on_ucc_framework/__init__.py
Last time release did not go because of the `semantic-release-replace-plugin` could not match the versions to update (because we released a beta version).
> ci: rollback versions to trigger the release

- splunk_add_on_ucc_framework/dashboard.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/data/ui/views/dashboard.xml
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/unit/test_dashboard.py
Related docs: https://docs.splunk.com/Documentation/Splunk/latest/SearchReference/Rest
Related PR: https://github.com/splunk/splunk-add-on-for-microsoft-365-defender/pull/314
> fix(dashboard): adds splunk_server=local when getting add-on version

- splunk_add_on_ucc_framework/commands/package.py
Fixes #900 - Adding ":gz" flag to [tarfile.open](https://docs.python.org/3/library/tarfile.html#tarfile.open) adds gzip compression on write.
> Fix: Add ":gz" flag to tarfile.open to add compression

- splunk_add_on_ucc_framework/global_config_validator.py
Fixes GitHub issue #902 
As discussed in #905, replaced the `warnings` library with `logger` to display warnings
> fix(warning): replaced warnings with logging library

- .github/workflows/build-test-release.yml
Pinning to this version to avoid testing with unreleased Splunk version.
> ui: pin splunk/addonfactory-test-matrix-action to 1.10

- docs/entity/components.md
- splunk_add_on_ucc_framework/schema/schema.json
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/unit/testdata/invalid_config_checkbox_groups_duplicate_field_in_options_groups.json
- tests/unit/testdata/invalid_config_checkbox_groups_duplicate_fields_in_options_rows.json
- tests/unit/testdata/invalid_config_checkbox_groups_undefined_field_used_in_groups.json
- tests/unit/testdata/valid_config.json
- ui/src/main/webapp/components/BaseFormView.jsx
- ui/src/main/webapp/components/CheckboxGroup/CheckboxGroup.stories.tsx
- ui/src/main/webapp/components/CheckboxGroup/CheckboxGroup.tsx
- ui/src/main/webapp/components/CheckboxGroup/CheckboxRow.tsx
- ui/src/main/webapp/components/CheckboxGroup/CheckboxRowWrapper.tsx
- ui/src/main/webapp/components/CheckboxGroup/checkboxGroup.utils.test.ts
- ui/src/main/webapp/components/CheckboxGroup/checkboxGroup.utils.ts
- ui/src/main/webapp/components/CheckboxGroup/checkboxGroupMocks.json
- ui/src/main/webapp/components/CheckboxGroup/checkboxGroupMocks.ts
- ui/src/main/webapp/components/CheckboxGroup/checkboxGroupValidation.test.ts
- ui/src/main/webapp/components/CheckboxGroup/checkboxGroupValidation.ts
- ui/src/main/webapp/components/ControlWrapper.jsx
- ui/src/main/webapp/constants/modes.ts
- ui/src/main/webapp/util/Validator.js
- ui/src/main/webapp/util/messageUtil.js
- input value restricted to numbers only to avoid handling encapsulation
- due to that, the only possible validation left - number. Regex and strings are removed.
- `text` field has renamed to `input`. Motivation: it is not a text anymore, rather number. Docs, tests, mocks are updated
- removed `options.enabled` property to disable fields because of perception that it sets defaultValue while it is used for disabling.
- for CREATE mode, checkbox group takes checkbox values from it's defaultValue. Value provided by form is ignored.
- for any mode, default value for `input` is taken from `input.defaultValue` if it is not provided as a form value `field1/value1`
> feat(CheckboxGroup): ADDON-61556 add defaultValue for checkbox

- poetry.lock
This PR updates urllib3 to v1.26.18 to resolve CVE (already done for main branch).
> fix: update urllib3

- splunk_add_on_ucc_framework/global_config_validator.py
- tests/unit/test_global_config_validator.py
- tests/unit/testdata/invalid_config_group_uses_fields_not_defined_in_entity.json
This PR adds one more additional validation for the "Groups Feature" (https://splunk.github.io/addonfactory-ucc-generator/advanced/groups_feature/): there can not be a group field which is not defined in the entity.
> feat: additional validations for the groups feature

- .gitignore
- .licenserc.yaml
- CONTRIBUTING.md
- README.md
- build-ui.sh
- docs/contributing.md
- pyproject.toml
- ui/.gitignore
- ui/README.md
- ui/package.json
- created bash script
- updated docs
> docs: adjust UI build commands

- .github/workflows/build-test-release.yml
`returntocorp` organization name was changed to `semgrep`.
> ci: returntocorp -> semgrep

- ui/.storybook/preview.tsx
- ui/.storybook/withSplunkTheme.tsx
SUI Storybook addon does not work with Storybook v7, so I created toolbar controls to control theme options. It is dropdowns, I tried but could not manage to make toggle. Seems like it is feasible only with addon (which I don't want to create).
I took parameters from [SUI docs](https://splunkui.splunk.com/Packages/react-ui). There is a settings icon in the right top corner to control theme variables.
> chore(storybook): ADDON-65440 add theme switcher

- ui/.yarnrc.yml
fixes changes registry across for the whole yarn.lock by renovate. Renovate bot works correctly since it yarnpkg.com is a default registry for yarn. Source: https://yarnpkg.com/configuration/yarnrc#npmRegistryServer
for example in #893
> chore(yarn): set npmjs.com as default registry

- ui/src/components/ControlWrapper.tsx
- ui/src/components/EntityModal.tsx
- ui/src/components/EntityPage.tsx
reverting the dynamic width of model, and moving to static width of 800px,
when the size is dynamic the model content is moved to right.
removing other styles as 
they can be replace with `labelWidth={240}`
dynamic current view: 
static new new/old view 800px:
> fix: revert to static width of modal

- ui/src/components/ControlWrapper.tsx
fixing issue of too small width of component group
setting control group max width to 100%, so component can be as long as parent element, along with limiting help message width to 320px (standard width of component)
> fix: add control group wrapper max width to 750px

- docs/quickstart.md
This feature was in review for some time and we forgot to update the minimum version it is available from.
> docs: update minimum version for verbose mode

- .github/workflows/build-test-release.yml
- poetry.lock
- pyproject.toml
This PR adds missing `colorama` dependency.
This commit (https://github.com/splunk/addonfactory-ucc-generator/pull/973/commits/ff3dcd74e8536ba6ad206011eeb795826c8ffb40) exposes the issue in the pipeline and [fbb71bd](https://github.com/splunk/addonfactory-ucc-generator/pull/973/commits/fbb71bd59598e1c4b1fb70600730c4151f158846) fixes it.
This issue should have been caught in the CI before making a release.
> fix: add missing colorama dependency

- docs/advanced/oauth_support.md
- ui/src/components/BaseFormView.jsx
- ui/src/components/EntityModal/EntityModal.test.tsx
- ui/src/components/EntityModal/TestConfig.ts
- ui/src/mocks/globalConfigMock.ts
- ui/src/types/globalConfig/entities.ts
As a replacement for account_hook.js for repo https://github.com/splunk/splunk-add-on-for-okta-identity-cloud
parent ticket https://splunk.atlassian.net/browse/ADDON-65747
fix for enable property for every entity/field and adding support of it for oauth fields
https://splunk.github.io/addonfactory-ucc-generator/entity/ 
Adding tests for default value in oauth fields, logic existed there it was just not permitted in schema.
> fix: fix enable for entities and add it for oauth

- .github/workflows/build-test-release.yml
Since develop is now our primary development branch - let's run all the tests when PR is created to develop.
> ci: run UI tests when PR is created against develop branch as well

- renovate.json
This PR changes Renovate's `rangeStrategy` to `bump` only for npm packages.
We don't want Renovate to bump Python packages because this package acts as a library.
> chore(renovate): bump package.json only

- docs/advanced/sub_description.md
- docs/configurations.md
- splunk_add_on_ucc_framework/schema/schema.json
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- ui/src/components/SubDescription/SubDescription.stories.tsx
- ui/src/components/SubDescription/SubDescription.test.tsx
- ui/src/components/SubDescription/SubDescription.tsx
- ui/src/mocks/globalConfigMock.ts
- ui/src/pages/Configuration/ConfigurationPage.jsx
- ui/src/pages/Input/InputPage.jsx
- ui/src/types/globalConfig/pages.ts
- ui/src/types/modules.d.ts
https://splunk.atlassian.net/browse/ADDON-67014
add possibility to create custom headers for inputs and configuration page.
Supports links and line breaks.
the idea for it is like that
```
"subDescription": {
"text": "Ingesting data from to Splunk Cloud?</br>Read our [[blogPost]] to learn more about Data Manager and it's availability on your Splunk Cloud instance.",
"links": [
{
"slug": "blogPost",
"link": "https://splk.it/31oy2b2",
"linkText": "blog post"
}
]
}
```
so a whole description is put inside  `subDescription.text` variable, with support of `</br>` as break lines.
also if you use [[blogPost]] and slugs it will look for a matching link there, if it finds it puts anchor element with all data, if not it remvoes squared brackets and puts that string clear in text
> feat: custom sub description for pages - ADDON-67014

- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/unit/test_install_python_libraries.py
The proper format in requirements.txt is `==`, not `=`.
> fix: typo in the error message

- .github/workflows/build-test-release.yml
The new password contains special characters which makes `poetry publish ...` step to fail.
I also manually remove new tag and release from GitHub so the new release can be created.
> ci: escape characters in PYPI_USERNAME and PYPI_TOKEN

- .github/workflows/build-test-release.yml
- NOTICE
- docs/CHANGELOG.md
- pyproject.toml
- splunk_add_on_ucc_framework/__init__.py
This PR reverts the bot's commit with a release information (so can bot can push it again).
And we don't need to quote PyPI secrets, tested [here](https://pypi.org/project/splunksplwrapper/1.1.5b1/).
> ci: finally fix the release

- docs/inputs/index.md
- mkdocs.yml
add description page to mkdocs, currently it is not added and displayed in docs
> docs: add sub description page to mkdocs.yml

- renovate.json
it updates `engines` field in package.json, but CI still uses the old version and fails
> chore(renovate): ignore nodejs required version updates

- splunk_add_on_ucc_framework/app_manifest.py
- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/global_config.py
- splunk_add_on_ucc_framework/schema/schema.json
- tests/smoke/test_ucc_build.py
- tests/testdata/test_addons/package_files_conflict_test/globalConfig.json
- tests/testdata/test_addons/package_global_config_configuration/globalConfig.json
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
This PR adds versions of used UCC framework to TA internal files for traceability.
see: [issue 983](https://github.com/splunk/addonfactory-ucc-generator/issues/983)
> feat: add UCC version to globalConfig

- .github/workflows/build-test-release.yml
skip THIRDPARTY build substeps for fork pull requests
> ci: fix pipeline for forks

- ui/src/components/BaseFormView.tsx
- ui/src/components/ConfigurationFormView.jsx
- ui/src/components/EntityModal/EntityModal.tsx
- ui/src/components/EntityPage.tsx
Enter for a form with single input triggers the form submission. [The specification](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission). The form submission was not properly handled.
- hook up on form submission by adding callback onSubmit for `<form />` element
- prevent default behavior (sending GET with formdata in params and redirect) and proceed with our handlers (validation and sending as JSON with AJAX)
- https://splunk.atlassian.net/browse/ADDON-61126
- https://splunk.atlassian.net/browse/ADDON-58706
Resolves #875
> fix(EntityModal): prevent Enter from submitting the form in Modal window

- ui/src/components/ControlWrapper.tsx
- ui/src/components/MultiInputComponent/MultiInputComponent.tsx
- ui/src/components/RadioComponent/RadioComponent.tsx
- ui/src/components/SingleInputComponent.tsx
- ui/src/components/TextAreaComponent/TextAreaComponent.tsx
- ui/src/components/TextComponent/TextComponent.tsx
We use SUI components but a lot of wrappers for it. These wrappers don't pass all required props to the target component including id attribute. This causes lack of connection between `label`'s `for` attribute and `input`s `id`.
Instead the `id` is set on the wrapper:
Pass id from wrapper to input.
- https://splunk.atlassian.net/browse/ADDON-68266
- closes #936
> fix(a11y): associate labels with inputs

- ui/.storybook/preview.tsx
Storybook deployed on GH pages is down due to it is looking for a JS service worker at the root path (`https://splunk.github.io/mockServiceWorker.js`) instead of subpath `https://splunk.github.io/addonfactory-ucc-generator/storybook/mockServiceWorker.js
The fix proposed in https://github.com/mswjs/msw-storybook-addon/issues/77 to add relative path instead of default absolute. I hope that would work
> chore(storybook): fix mock service worker path

- ui/src/components/ControlWrapper/ControlWrapper.tsx
> fix: return back div wrapper that shifts layout

- .github/workflows/build-test-release.yml
It waits the following jobs
- test-ui
- build-test-addon-openapi-client
- storybook-screenshots
and fails if something fails. It will be useful for setting required checks for PRs
> ci: add all-checks to summarize tests

- docs/entity/index.md
- mkdocs.yml
- Add a bit of descriptions for common options
- pymdownx.superfences for enabling code highlighting 
Related to #1101
> docs(entity): clarify options params

- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/splunk_ta_uccexample_account.conf.spec
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
- tests/ui/pages/account_page.py
- tests/ui/test_configuration_page_account_tab.py
Added UI tests that cover account page. These tests were [removed from ServiceNow add-on](https://github.com/splunk/splunk-add-on-for-servicenow/pull/710).
> test: add more ui tests for account page

- splunk_add_on_ucc_framework/schema/schema.json
- tests/unit/testdata/valid_config.json
- ui/src/components/BaseFormView.tsx
- ui/src/components/CheckboxGroup/checkboxGroupRequiredMocks.json
- ui/src/components/CheckboxGroup/stories/CheckboxGroupInputPage.stories.tsx
- ui/src/components/CheckboxGroup/stories/__images__/CheckboxGroup-required-view-chromium.png
- Implemented a new checkboxgroup component named "Required checkbox example" with required validation.
- Updated "schema.json" and "valid_config.json" to include the "required" attribute.
- Addressed the issue where the "required" validation was not functioning correctly when only a single field was present in the form.
> feat(CheckboxGroup): add support for required field

- ui/webpack.config.js
disable warning about lack of licenses in packages:
```
WARNING in license-webpack-plugin: could not find any license file for styled-components. Use the licenseTextOverrides option to add the license text if desired.
WARNING in license-webpack-plugin: could not find any license file for @mdhnpm/rgb-hex-converter. Use the licenseTextOverrides option to add the license text if desired.
WARNING in license-webpack-plugin: could not find any license type for uuid-v4 in its package.json
WARNING in license-webpack-plugin: could not find any license file for uuid-v4. Use the licenseTextOverrides option to add the license text if desired.
WARNING in license-webpack-plugin: could not find any license type for maplibre-gl in its package.json
```
> chore(webpack): disable throwing warnings about lack of licenses

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/docs.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This PR adds a new GitHub issue for documentation updates.
> docs(governance): add GitHub issue type for documentation updates

- .gitignore
- docs/entity/components.md
- splunk_add_on_ucc_framework/schema/schema.json
- ui/src/components/FileInputComponent/FileInputComponent.test.tsx
- ui/src/components/FileInputComponent/FileInputComponent.tsx
- ui/src/types/globalConfig/entities.ts
Add configurable support for none text files, via encoding content to base64 string.
https://splunk.atlassian.net/browse/ADDON-69993
> feat: file input component, supports base64 encoding

- splunk_add_on_ucc_framework/commands/build.py
- splunk_add_on_ucc_framework/global_config.py
- tests/unit/commands/rest_builder/test_generate_import_declare_test.py
- tests/unit/commands/test_build.py
- tests/unit/conftest.py
- tests/unit/test_dashboard.py
- tests/unit/test_global_config.py
- tests/unit/test_global_config_update.py
- tests/unit/test_global_config_validator.py
- tests/unit/test_install_python_libraries.py
**ADDON-70444**
Refactor of globalConfig class to self-determine json or yaml file type. From now on, this class accepts only one parameter - path to the configuration file.
Removed _is_global_config_yaml_ parameter from GlobalConfig class. 
Added determination of file type inside __init__ of GlobalConfig
The same behavior as before the changes was maintained
no impact
> refactor: GlobalConfig class to self-determine json and yaml

- ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
- ui/src/components/BaseFormView/stories/__images__/BaseFormView-both-oauth-chromium.png
- ui/src/components/BaseFormView/stories/__images__/BaseFormView-oauth-oauth-chromium.png
- ui/src/components/BaseFormView/stories/__images__/BaseFormView-ouath-basic-chromium.png
- ui/src/components/BaseFormView/stories/globalConfigs/configPageOauth.ts
- ui/src/components/ControlWrapper/ControlWrapper.tsx
**Issue number:** [ADDON-68506](https://splunk.atlassian.net/browse/ADDON-68506)
[UCC UI] Show asterisk for all required fields
Fix bug that by default Asterix was not added to any field . Right now by default required is true for oauth fields and false for any other fields. (If field contains `oauth_field` property (every oauth field contains it), it is marked with asterix by default, unless specified differently.
Pass required parameter explicitly to wrapper.
Asterix should be displayed correctly for oauth fields.
> fix: explicitly pass required field

- splunk_add_on_ucc_framework/schema/schema.json
- splunk_add_on_ucc_framework/templates/globalConfig.json.init-template
- splunk_add_on_ucc_framework/templates/input.helper-init-template
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/globalConfig.json
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/bin/demo_input_helper.py
- ui/src/types/globalConfig/pages.ts
1. A change in globalConfig.json to enable input module helper by default.
2. Added lines for monitoring.
The feature will work as before during the build stage but the init scripts will contain proper values. Before that, the helper module got generated in the init stage without a proper parameter in the config.
> feat: Improve input helper module init scripts

- docs/CHANGELOG.md
[This commit](https://github.com/splunk/addonfactory-ucc-generator/commit/44cbcd9ceedee0865f5864d9912a7ab18e331d8f) introduces the issues
```
markdownlint.............................................................Failed
- hook id: markdownlint
- exit code: 1
docs/CHANGELOG.md:3 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
docs/CHANGELOG.md:8 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```
That causes pipeline failures
Fix the symptoms, but not  aroot cause
No UX changes
> chore(CHANGELOG): fix pre-commit markdownlint issues

- .github/workflows/build-test-release.yml
- tests/unit/test_global_config_validator.py
Github actions marks jobs as succeeded if it failed with `continue-on-error`. There is no other way to check if jobs were actually failed. That the reason why adding `test-unit` to `all-checks` did not have any effect.
Add output variable for every `continue-on-error` jobs that helps to identify failed ones during `all-checks`. You might check the result when tests are broken: https://github.com/splunk/addonfactory-ucc-generator/actions/runs/9365665879/job/25782687764#step:3:1
No impact
> ci(workflow): add test-unit to required checks

- splunk_add_on_ucc_framework/commands/rest_builder/endpoint/oauth_model.py
- splunk_add_on_ucc_framework/commands/rest_builder/global_config_builder_schema.py
- splunk_add_on_ucc_framework/global_config.py
- splunk_add_on_ucc_framework/templates/oauth.template
- tests/testdata/expected_addons/expected_output_global_config_configuration/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_oauth.py
- tests/unit/commands/rest_builder/test_global_config_builder_schema.py
**Issue number:** ADDON-58434
The OAuth RH template is updated. It now fetches the configured log level in the add-on and writes logs as per the level set.
Using this feature, developers wouldn't have to update their OAuth RH file in their source code to get the log level set by the user in the add-on.
> fix(oauth): set loglevel in oauth rh template to use log level set in add-on

- docs/dashboard.md
- splunk_add_on_ucc_framework/dashboard.py
- splunk_add_on_ucc_framework/schema/schema.json
- splunk_add_on_ucc_framework/templates/errors_tab_definition.json
- splunk_add_on_ucc_framework/templates/input.helper-init-template
- tests/testdata/expected_addons/expected_addon_after_init/demo_addon_for_splunk/package/bin/demo_input_helper.py
- tests/unit/expected_results/errors_tab_definition.json
- tests/unit/expected_results/overview_definition.json
- ui/package.json
- ui/src/components/DashboardInfoModal/DashboardInfoModal.tsx
- ui/src/pages/Dashboard/DataIngestion.tsx
- ui/src/pages/Dashboard/Error.tsx
- ui/src/pages/Dashboard/ErrorPageConfig.ts
- ui/src/pages/Dashboard/dashboardStyle.css
- ui/src/pages/Dashboard/utils.tsx
- ui/src/types/globalConfig/pages.ts
- ui/src/types/modules.d.ts
- ui/yarn.lock
**Issue number:[ADDON-68670](https://splunk.atlassian.net/browse/ADDON-68670)**
Error section has been expanded to include a division into error categories.
* Error categories were added to error chart
* Error categories were added to error event table
* Multiselect filter was added to error event table
The user will have access to a more detailed chart and table including types of errors.
The user will now be able to filter the results in the table using multi-select with specific error types as filters.
> feat(dashboard): add error categories to chart and event table in the error panel

- .markdownlint.yaml
Allow 2 empty line in markdown linter
>
>
> docs: allow 2 blank lines in markdown files

- docs/dashboard.md
- splunk_add_on_ucc_framework/dashboard.py
- splunk_add_on_ucc_framework/schema/schema.json
- tests/unit/test_dashboard.py
**Issue number:[ADDON-71696](https://splunk.atlassian.net/browse/ADDON-71696)**
Added possibility to change default queries used by monitoring dashboard for filtering license_usage.log file.
Added new settings in globalConfig.json file for dashboard for custom filtering:
* **determine_by** -> is used to determine the filtering basis. It can take one of 4 possible arguments: (“source”, “sourcetype”, “host”, “index”).
* **search_condition** -> list of strings type parameter where you can provide elements that will be used to filter events in the license usage file.
The user can use custom filters to search the license_usage file to determine the addon's data volume usage using globalConfig.json file:
```
"dashboard": {
"panels": [
{
"name": "custom"
}
],
"settings": { …
```
> feat(dashboard): add custom filtering options for the license_usage file

- ui/src/pages/Dashboard/stories/DashboardPage.stories.tsx
- ui/src/pages/Dashboard/stories/__images__/DashboardPage-dashboard-page-view-chromium.png
the story does not wait until dashboard finishes loading before taking a screenshot. It causes random mismatches of screenshots because sometimes it loads before taking a screenshot, sometimes it does not.
story waits for the dashboard to appear on the page before taking a screenshot
No effect 
> tests: make dashboard page tests more deterministic

- splunk_add_on_ucc_framework/global_config_validator.py
- tests/unit/conftest.py
- tests/unit/test_global_config_validator.py
Global Config Schema contains unicode characters inside descriptions. By default, it is open using the default system encoding. This change allows to use the schema regardless of the default encoding, as it is always read using utf-8.
This allows users to use UCC on different platforms with default encodings different than utf-8.
> fix: allow using Global Config Validator regardless of the default encoding

- docs/CHANGELOG.md
Added missing `#`
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details> 
> docs(CHANGELOG): fix title level for 5.47.0

- splunk_add_on_ucc_framework/schema/schema.json
**Issue number:**[ADDON-72535](https://splunk.atlassian.net/browse/ADDON-72535) 
Schema changes that allow valueField inside globalConfig file
Allow optional string property valueField inside globalConfig file
User can build with valueField in globalConfig
> fix: schema for mapping custom api value

- tests/ui/test_input_page.py
**Issue number:** None
The test uses a tolerance of ±5 pixels to ensure that the height is within an acceptable range, rather than requiring an exact pixel match. This makes the test more robust and less likely to fail due to minor, non-critical differences in rendering.
No changes
> test(textarea_height): test height within a range instead of certain amount of pixels

- splunk_add_on_ucc_framework/commands/modular_alert_builder/arf_template/default_html_theme/textarea.html
- splunk_add_on_ucc_framework/global_config_validator.py
**Issue number:[ADDON-68244](https://splunk.atlassian.net/browse/ADDON-68244)**
Add basic textarea field to alerts.
Added textarea.html file for rendering textarea field in alerts.
The user can now use textarea field in alerts. Since it's basic html template additional options like rowsMin and rowsMax won't do anything.
> feat: add basic textarea field to alerts

- poetry.lock
- pyproject.toml
Updated the version of splunk-conf-parser-lib library from 0.4.2 to 0.4.3.
> removes duplicate newlines only when there is content to be written.
> chore(deps): updated addonfactory-splunk-conf-parser-lib version

- ui/src/types/globalConfig/alerts.ts
#1135 changed the JSON schema and caused inconsistency between two schemas
The PR adds corresponding changes to zod schema
The runtime warning about incorrect globalConfig caused by `adaptiveResponse` should disappear. 
> chore: fix adaptiveResponse in runtime schema

- splunk_add_on_ucc_framework/generators/conf_files/create_app_conf.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/app.conf
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/testdata/test_addons/package_global_config_everything/package/app.manifest
https://splunk.atlassian.net/browse/ADDON-75546
description was used instead of title, wrong text was displayed
change description into title
Title correctly displayed
> fix: use title for app conf

- ui/package.json
- ui/yarn.lock
Apply 'the fix' from splunk visualizations team
https://splunk.atlassian.net/browse/SCP-70409?focusedCommentId=15609860
- Override module resolution to bring v3 instead of required v2. Potentially, it may break functionality
-
> chore(deps): add module resolution for d3-color and d3-interpolate

- .github/workflows/automatic_doc_generation.yml
- .github/workflows/build-test-release.yml
- .github/workflows/build-ui.yml
- .github/workflows/docs.yml
- .github/workflows/storybook-visual.yml
Moving from ubuntu latest to ubuntu 22.04
latest ubuntu moved to 24.04 (https://github.com/actions/runner-images/issues/10636)
Current issue is Ubuntu 24.04 does not cache python 3.7.
whats causing jobs to fail:
https://github.com/splunk/addonfactory-ucc-generator/actions/runs/11314103564/job/31463721491
ubuntu-22.04 is used instead of ubuntu-latest
no changes
> chore: use ubuntu ubuntu-22.04

- docs/advanced/oauth_support.md
- splunk_add_on_ucc_framework/schema/schema.json
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/bin/splunk_ta_uccexample_rh_account.py
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/ui/pages/account_page.py
- tests/ui/test_configuration_page_account_tab.py
- ui/src/types/globalConfig/entities.ts
https://splunk.atlassian.net/browse/ADDON-61740
allows validators to oauth fields
allow validators array inside globalConfig.json scheme
right now oauth fields can be validated
> feat: allow validators for oauth fields

- splunk_add_on_ucc_framework/global_config_validator.py
- splunk_add_on_ucc_framework/schema/schema.json
**Issue number:[ADDON-73358](https://splunk.atlassian.net/browse/ADDON-73358)**
Alerts used to have only one entity and were created using the same schema where the type was based on the enum. Additional validation of whether a given parameter for a specific enum is correct was done on the backend. Now each entity has its own definition and no additional validation is needed on BE.
Extracted AlertsEntity into 6 schemas, one for each enum.
Removed BE validation for required parameters.
No impact
> refactor: extract alert entity

- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/unit/test_install_python_libraries.py
Remove unused `_check_ucc_library_in_requirements_file` function from `install_python_libraries.py`. Now we check for `splunktaucclib` after we install all Python packages from `requirements.txt`, not by reading what's inside of `requirements.txt` file.
Removing unused function and corresponding test cases.
N/A
> refactor: remove unused function

- ui/src/components/BaseFormView/BaseFormView.tsx
- ui/src/components/ConfigurationFormView.jsx
- ui/src/components/DeleteModal/DeleteModal.test.tsx
- ui/src/components/DeleteModal/DeleteModal.tsx
- ui/src/components/MultiInputComponent/MultiInputComponent.tsx
- ui/src/components/SingleInputComponent/SingleInputComponent.tsx
- ui/src/components/table/TableWrapper.tsx
- ui/src/pages/Configuration/tests/ConfigurationPage.test.tsx
- ui/src/public/mockServiceWorker.js
- ui/src/types/modules.d.ts
- ui/src/util/__mocks__/util.ts
- ui/src/util/axiosCallWrapper.ts
- ui/src/util/util.ts
**Issue number:** ADDON-75718
- Encoded all dynamic parameters that comes into URL path, including the ones that come from user input (as input name) and from globalConfig.json
- removed serviceName from axiosCallWrapper since it is leaking abstraction
- unmocked generateEndPointUrl that causes small changes in tests
It may only impact users if they put special symbols to entity names and expect it will go directly as part of URL.
> refactor(api): encode URL path

- .github/actions/cached-ui-deps/action.yml
- .github/workflows/build-ui.yml
- .github/workflows/docs.yml
- .github/workflows/storybook-visual.yml
This PR updates the GitHub workflow for caching Yarn dependencies. The previous workflow involved manually installing Yarn, determining the cache directory, and using the actions/cache action to cache dependencies. The updated workflow simplifies this process by leveraging the actions/setup-node action with built-in Yarn caching support.
Reference: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
No changes
> ci: simplify GitHub workflow for caching Yarn deps

- renovate.json
Renovate should not update ubuntu versions, related to #1374
Disable updates for ubuntu
No changes
> chore(renovate): ignore ubuntu updates for GitHub Actions

- .github/actions/cached-ui-deps/action.yml
- .github/workflows/build-test-release.yml
- .github/workflows/build-ui.yml
- .github/workflows/docs.yml
- .github/workflows/storybook-visual.yml
Remove all hardcoded values from CI jobs and specify a path to package.json
<details><summary>Log</summary>
<p>
Resolved ui/package.json as >=20.10.0
Found in cache @ /opt/hostedtoolcache/node/20.18.0/x64
Environment details
node: v20.18.0
npm: 10.8.2
yarn: 1.22.22
</p>
</details> 
No changes
> ci: parse node version from package.json

- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/unit/test_install_python_libraries.py
**Issue number:[ADDON-74237](https://splunk.atlassian.net/browse/ADDON-74237)**
Added splunktaucclib version checking.
* new method _check_libraries_required_for_ui was added to check if splunktaucclib is installed and has proper version
The build process will be canceled if an incorrect version of the splunktaucclib library is used.
> feat: require splunktaucclib 6.4.0 during the build phase

- ui/src/components/ControlWrapper/ControlWrapper.tsx
- ui/src/components/SingleInputComponent/SingleInputComponent.tsx
> Use empty string when single select does not have value.
> No changes. It removes error from console.
> chore: single select with default empty string value

- ui/src/components/DeleteModal/DeleteModal.test.tsx
- ui/src/components/DeleteModal/DeleteModal.tsx
- Add tests to check if network errors handles correctly
- It revealed it does not, so I fixed it
No changes
> test(delete-modal): add network error test case

- ui/jest.config.ts
**Issue number:** - 
Coverage 
File                                    | % Stmts | % Branch | % Funcs | % Lines
All files                               |   66.81 |    57.74 |   65.09 |   67.14 |  
File                  | % Stmts | % Branch | % Funcs | % Lines
All files             |   66.32 |    57.74 |   65.54 |   66.65 |
No changes
> test(coverage): exclude untestable types from coverage

- .github/workflows/build-test-release.yml
- poetry.lock
- pyproject.toml
Adding an explicit support for Python 3.12.
(I tested Python 3.13 but it does not work yet because of `lxml` does not support 3.13 yet).
N/A
> chore(pyproject): explicitly specify supported Python versions

- tests/testdata/expected_addons/expected_output_global_config_everything/.appinspect_api.expect.yaml
Reverts splunk/addonfactory-ucc-generator#1427
It is not expected anymore, causing ci failures
https://github.com/splunk/addonfactory-ucc-generator/actions/runs/11820162390/job/32932305072
> Revert "ci: add expected failure for appinspect-api check"

- .github/PULL_REQUEST_TEMPLATE.md
- Add PR type to promote smaller PRs
- Changed wording
No changes
> chore(pull request template): add PR type 

- ui/src/components/SingleInputComponent/SingleInputComponent.test.tsx
- ui/src/util/api.ts
**Issue number:** ADDON-76586
Regression from #1424. There was a Null Pointer Exception due to `undefined` values of `dependencyValues` and calling `.toString()` on `undefined`. NPE itself is not a problem since it is silenced, but the request is not made due to this and "No manches" is shown
- Filter out null and undefined values (as `axios` does)
- Add tests covering this bug
Ability to see options fetching from the server
> fix(select): fetching options when some dependency is null

- ui/.eslintrc.js
- ui/src/components/SingleInputComponent/SingleInputComponent.test.tsx
Every PR has this
but it is just a warning, so it does not fail the build
- eslint considers this as an error instead of warning
- fix the issue by adding explicit expects
No change
> test(SingleInputComponent): add expect and fix warning

- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/smoke/test_ucc_build.py
- tests/unit/test_install_python_libraries.py
**Issue number:** [ADDON-76503](https://splunk.atlassian.net/browse/ADDON-76503)
Compiled Python files are created when UCC checks using pip whether a library is installed.
This prevents it from doing that.
Output directory with lib dir that does not contain `__pycache__`.
> feat: do not create __pycache__ in lib dir

- poetry.lock
- pyproject.toml
Allow `packaging` from a version "23.0".
To reproduce the issue run
```bash
pip install splunk-add-on-ucc-framework==5.53.1
pip install splunk-appinspect==3.8.1
```
You should see
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
splunk-add-on-ucc-framework 5.53.1 requires packaging==24.0, but you have packaging 23.0 which is incompatible.
```
in your console.
Developers can install latest version of both UCC and Splunk AppInspect CLI in the same virtual environment.
> fix: allow packaging from 23.0

- renovate.json
**Issue number:** - 
Set renovate to ignore bumping python version (like in #1478). Specifically, this change
```toml
[tool.poetry.dependencies]
python = ">=3.13,<3.14"
```
No changes
> chore(renovate): ignore python update

- renovate.json
Ask renovate to ignore all mkdocs* packages from bumping minor and major versions.
> chore(renovate): ignore mkdocs update

- ui/src/components/ControlWrapper/ControlWrapper.tsx
- ui/src/components/ControlWrapper/stories/ControlWrapper.stories.ts
- ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-with-modifications-chromium.png
- ui/src/components/ControlWrapper/stories/__images__/ControlWrapper-with-modifications-make-required-chromium.png
- ui/src/components/ControlWrapper/test/ControlWrapper.test.tsx
https://splunk.atlassian.net/browse/ADDON-77024 
Correctly reflects component required property after modifications on value change are applied.
Fixes error that verified if required start should be displayed.
Users see required star correct next to elements that are required currently.
> fix: required star visibility when using modify prop

- .github/workflows/build-test-release.yml
- tests/testdata/expected_addons/expected_output_global_config_everything/.appinspect_api.expect.yaml
- tests/testdata/test_addons/package_global_config_everything/package/app.manifest
* Updating license path in "everything" add-on to pass AppInspect API check.
* Removed `check_for_compiled_python` known issue from ignore file.
* Run `appinspect-api` for every PR.
N/A
> chore(appinspect-api): make it pass

- .markdownlint.yaml
- docs/CHANGELOG.md
N/A
Configuration for documentation lint.
use asterisk as bold sign
N/A
> docs: highlight underscores as code block

- docs/entity/modifyFieldsOnValue.md
- splunk_add_on_ucc_framework/global_config_validator.py
- tests/unit/test_global_config_validator.py
- tests/unit/testdata/invalid_config_with_modification_circular_modifications.json
- tests/unit/testdata/invalid_config_with_modification_for_field_itself.json
- tests/unit/testdata/valid_config_with_modification_on_value_change.json
- ui/src/components/BaseFormView/stories/BaseFormView.stories.tsx
- ui/src/components/BaseFormView/stories/__images__/BaseFormView-field-modify-itself-after-mods-chromium.png
- ui/src/components/BaseFormView/stories/__images__/BaseFormView-field-modify-itself-chromium.png
- ui/src/components/BaseFormView/tests/BaseFormView.test.tsx
- ui/src/components/BaseFormView/tests/BaseFormViewModifications.test.tsx
- ui/src/components/BaseFormView/tests/configMocks.ts
https://splunk.atlassian.net/browse/ADDON-76687 
Remove verification to block field from applying modification to itself after value change.
It is not a risk to allow users to modify field itself as we should be concerned only for value. (it is still not a problem but seems like a bad approach to solving problems).
It also enables circular dependencies in case where modifications are not about value. (modifying values still should work good but seems like a bad practise)
User can right now modify state of field by applying changes to currently edited field, it allows to create ie. much more useful labels and help messages referencing value change.
> feat(modifyFieldsOnValue): enable field to modify itself

- .github/workflows/build-test-release.yml
Rollback plunk-appinspect from the latest 3.9.0 to 3.8.1. 
3.9.0 does not support Python 3.7
No changes
> ci: rollback splunk-appinspect to 3.8.1

- .github/workflows/build-test-release.yml
Reverts splunk/addonfactory-ucc-generator#1527
New version of `splunk-appinspect` was released and it fixes the issue introduced in 3.9.0 so we can revert this change.
> revert: "ci: rollback splunk-appinspect to 3.8.1"

- splunk_add_on_ucc_framework/global_config_update.py
- tests/testdata/test_addons/package_files_conflict_test/globalConfig.json
- tests/testdata/test_addons/package_global_config_everything/globalConfig.json
- tests/testdata/test_addons/package_global_config_everything_uccignore/globalConfig.json
- tests/testdata/test_addons/package_global_config_multi_input/globalConfig.json
- tests/testdata/test_addons/package_global_config_only_one_tab/globalConfig.json
- tests/unit/test_global_config_update.py
**Issue number:** ADDON-77791
Prevent unnecessary updates to the globalConfig file. To reproduce it - create a fresh add-on using `init -> build` commands and you shall see multiple log lines with "Updated globalConfig schema to version <version>" which should not be needed as it is a completely fresh add-on which should already use the latest version of the globalConfig file.
The old logic relies on `_uccVersion` field which is also no longer present (#1519) in the globalConfig file.
The new logic explicitly declares a list of supported schema versions (which is not the most elegant solution) and uses "0.0.0" in case `schemaVersion` is not known (this is possible in add-ons built with older versions of Add-on Builder).
No unnecessary …
> fix: prevent unnecessary updates to the globalConfig file

- ui/src/components/CustomControl/CustomControl.test.tsx
- ui/src/components/EntityModal/EntityModal.test.tsx
- ui/src/components/InteractAllStatusButton.test.tsx
- ui/src/components/table/tests/CustomTableRow.test.tsx
- ui/src/components/table/tests/TableExpansionRow.test.tsx
React 18 throws warning about unwrapped side effects in `act`. 
- Add implicit waiting when CustomControl finishes loading
- proper usage of userEvent: [docs](https://testing-library.com/docs/user-event/intro/#writing-tests-with-userevent)
No changes
> test: prevent warnings about unhandled side effects

- ui/.storybook/preview-head.html
- ui/.storybook/test-runner.ts
Sometimes Storybook takes a screenshot before the font is loaded. That results in the screen without any text on it. Then it commits this screenshot.
The problem is that the font loads far after the page load finish 
I added waitForPageReady that includes networkidle. I am not sure if this solve the problem, but let's see.
No changes
> chore(storybook): waitForPageReady for CI

- tests/ui/conftest.py
Internal issues from RUM script causes CIs fails
```
LogSource.CONSOLE_API - https://cdn.signalfx.com/o11y-gdi-rum/v0.16.5/splunk-otel-web.js 0:124824 TypeError: Failed to fetch
E               at https://cdn.signalfx.com/o11y-gdi-rum/v0.16.5/splunk-otel-web.js:1:[105](https://github.com/splunk/addonfactory-ucc-generator/actions/runs/13048620722/job/36404051731#step:8:106)313
```
https://github.com/splunk/addonfactory-ucc-generator/actions/runs/13048620722/job/36404051731
Add part of the error to ignore list to not fail e2e tests
No changes
> ci(test): ignore errors caused by RUM scripts

- ui/src/components/table/TableExpansionRowData.jsx
- ui/src/components/table/tests/TableExpansionRowData.test.tsx
Correctly verify status value.
Before:
Status is `true` as input is disabled: true
Status is `false` as input is disabled: false
After:
Status is `true` as input is disabled: true
Status is `false` as input is disabled: false
User can see status value.
> fix: correctly display status in more info

- .github/workflows/npm-publish.yml
I want to publish pre-release versions of npm package before actual release to let me test the package from other repositories
Add ability to bump a version of package.json. The bumped version would not be commited
https://www.npmjs.com/package/@splunk/add-on-ucc-framework?activeTab=versions
No changes
> ci(npm): allow to publish prerelease with manual workflow run

- .github/workflows/build-test-release.yml
- .github/workflows/npm-publish.yml
- The publish job is failed with an error
```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm error code EUSAGE
npm error Provenance generation in GitHub Actions requires "write" access to the "id-token" permission
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-02-18T16_29_20_197Z-debug-0.log
```
- It is now allowed to manually publish NPM package without a bump
- Give permissions for NPM publish during a regular build
- Add ability to publish version from the repository without a bump for a manual workflow
No changes
> ci(npm): fix release publish command

- .github/workflows/ta-tests.yml
**Issue number:** ADDON-76776
Tests multiple Splunk add-ons using the built UCC package, with a matrix strategy for different target repositories.
> ci: build TAs with current version of UCC

- ui/src/components/BaseFormView/BaseFormView.tsx
- ui/src/types/components/BaseFormTypes.ts
- ui/src/types/components/CustomHookClass.ts
- ui/src/types/components/shareableTypes.ts
- ui/src/util/Validator.js
- ui/src/util/tests/validators.test.ts
Small change:
instead of 
```
error = getFormattedMessage(11, rawStr);
```
use rawStr with []
```
error = getFormattedMessage(11, [rawStr]);
```
+ add js doc types to validation function
Display error for incorrect validator correctly
> fix(validation): correctly display error in save validator fnc

- splunk_add_on_ucc_framework/install_python_libraries.py
- tests/unit/test_install_python_libraries.py
**Issue number:** [ADDON-78105](https://splunk.atlassian.net/browse/ADDON-78105)
Improve error message for library installation process.
Added error message log to `_pip_install` method.
Better understanding why `ucc-gen` build failed due to `CouldNotInstallRequirements` error.
> refactor: improve installation error message

- ui/src/util/Validator.js
- ui/src/util/tests/validators.test.ts
https://splunk.atlassian.net/browse/ADDON-78393 
N/A do not throw error if number undefined and not required.
When copying entity right now correctly verify number value.
> fix(validation): correctly validate empty not required data

- docs/entity/modifyFieldsOnValue.md
Update documentation of modifications regarding to comments in previous PR.
N/A
> docs: use Admonition instead of details in modifications description

- splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/inputs.conf.spec
- tests/unit/generators/conf_files/test_create_inputs_conf.py
**Issue number:** [ADDON-78536](https://splunk.atlassian.net/browse/ADDON-78536)
Help links will no longer be written in inputs.spec files as those parameters cannot be set anyway.
Changes in generated spec files but no functionality is changed. I.e. we are skipping parameters that do nothing anyway.
> feat: skip help links in inputs.conf.spec

- splunk_add_on_ucc_framework/generators/conf_files/create_inputs_conf.py
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/README/inputs.conf.spec
- tests/unit/generators/conf_files/test_create_inputs_conf.py
Reverts splunk/addonfactory-ucc-generator#1630
The PR was merged due to lack of required checks, this caused test-ui failing in develop
> revert: "feat: skip help links in inputs.conf.spec"

- ui/src/components/CheckboxGroup/CheckboxGroup.tsx
- ui/src/components/CheckboxTree/CheckboxTree.tsx
- ui/src/components/MenuInput/MenuInput.tsx
- ui/src/components/table/CustomTableRow.tsx
**Issue number:** ADDON-78814
SUI 5 deprecated some props
- icon -> startAdornment for Menu.Item
- removed appearance="flat" since it is deprecated, and it is a default anyway
- "pill" to "subtle"
No visual changes
> chore(button,menu): remove deprecated appearance and icon properties

- .github/workflows/ta-tests.yml
> [!WARNING]
> Code was generated entirely by GAI
This PR enhances the reliability of the TA-tests GitHub Actions workflow by implementing retry logic for Poetry dependency installation commands. These changes address intermittent "Package Not Found" errors that occur during dependency resolution, which previously required manual workflow re-runs.
- Added retry logic with a fixed number of attempts to the Poetry dependency installation steps
- Set a maximum of 3 retry attempts for each Poetry command that involves dependency resolution
- Implemented separate retry blocks for UCC framework installation and splunktaucclib installation
- Added short fixed-interval delays between retries to allow for network/CDN stabilization …
> ci(ta-tests): add retry logic poetry install

- splunk_add_on_ucc_framework/global_config.py
- tests/unit/test_global_config.py
- tests/unit/test_global_config_validator.py
**Issue number:** ADDON-78488
This feature allows UCC to initialize a `GlobalConfig` from `app.manifest` file. This will be later used to create a `GlobalConfig` if there is no such exists which enables UCC to support `.conf`-only add-ons in a better way.
N/A
> feat: introduce GlobalConfig.from_app_manifest

- splunk_add_on_ucc_framework/templates/html_templates/alert_html_skeleton.template
- splunk_add_on_ucc_framework/templates/html_templates/checkbox.html
- splunk_add_on_ucc_framework/templates/html_templates/dropdownlist_splunk_search.html
- splunk_add_on_ucc_framework/templates/html_templates/radio.html
- splunk_add_on_ucc_framework/templates/html_templates/text.html
- splunk_add_on_ucc_framework/templates/html_templates/textarea.html
- tests/testdata/expected_addons/expected_output_global_config_everything/Splunk_TA_UCCExample/default/data/ui/alerts/test_alert.html
Used spaces instead of tabs for `HTML templates`.
No change in User experience.
> chore: use spaces instead of tabs for HTML templates

- ui/src/components/TextAreaComponent/TextAreaComponent.tsx
- ui/src/components/TextAreaComponent/stories/TextAreaComponent.stories.tsx
- ui/src/components/TextAreaComponent/stories/__images__/TextAreaComponent-encrypted-chromium.png
- ui/src/components/TextAreaComponent/stories/__images__/TextAreaComponent-un-encrypted-chromium.png
- ui/src/components/TextComponent/TextComponent.tsx
https://splunk.atlassian.net/browse/ADDON-81688
Masks text area data when encrypted.
Data in text area are masked into many ***** when using it for encrypted fields.
Unfortunately works well only for 
Chrome	✅ Yes
Safari	✅ Yes
Opera	✅ Yes
Edge (Chromium)
Does not work for
Firefox	❌ No
Internet Explorer	❌ No
Old Edge (EdgeHTML)	❌ No
Encrypted = true:
Encrypted = false:
> feat(textarea): mask data when encrypted
